In [1]:
!pip uninstall -y kaggle-environments
!pip uninstall -y dopamine-rl

Found existing installation: kaggle-environments 1.17.6
Uninstalling kaggle-environments-1.17.6:
  Successfully uninstalled kaggle-environments-1.17.6
Found existing installation: dopamine_rl 4.1.2
Uninstalling dopamine_rl-4.1.2:
  Successfully uninstalled dopamine_rl-4.1.2

In [2]:
!pip install ale-py --upgrade
!pip install gymnasium==0.28.1
!pip install 'stable-baselines3[extra]'
!pip install yfinance pandas
!pip install ta
!pip install PyPortfolioOpt
!pip install wandb

Requirement already satisfied: ale-py in /usr/local/lib/python3.11/dist-packages (0.11.1)
Collecting ale-py
  Downloading ale_py-0.11.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: numpy>1.20 in /usr/local/lib/python3.11/dist-packages (from ale-py) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>1.20->ale-py) (2.4.1)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>1.20->ale-py) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>1.20->ale-py) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>1.20->ale-py) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>1.20->ale-py) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>1.20->ale-py) (2024.2.0)
Downloading ale_py-0.11.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 42.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: ale-py
  Attempting uninstall: ale-py
    Found existing installation: ale-py 0.11.1
    Uninstalling ale-py-0.11.1:
      Successfully uninstalled ale-py-0.11.1
Successfully installed ale-py-0.11.2
Collecting gymnasium==0.28.1
  Downloading gymnasium-0.28.1-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium==0.28.1) (1.26.4)
Collecting jax-jumpy>=1.0.0 (from gymnasium==0.28.1)
  Downloading jax_jumpy-1.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium==0.28.1) (3.1.1)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium==0.28.1) (4.14.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium==0.28.1) (0.0.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium==0.28.1) (2.4.1)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.21.0->gymnasium==0.28.1) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.21.0->gymnasium==0.28.1) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.21.0->gymnasium==0.28.1) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.21.0->gymnasium==0.28.1) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.21.0->gymnasium==0.28.1) (2024.2.0)
Downloading gymnasium-0.28.1-py3-none-any.whl (925 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 925.5/925.5 kB 13.1 MB/s eta 0:00:0000:010:01
Downloading jax_jumpy-1.0.0-py3-none-any.whl (20 kB)
Installing collected packages: jax-jumpy, gymnasium
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 0.29.0
    Uninstalling gymnasium-0.29.0:
      Successfully uninstalled gymnasium-0.29.0
Successfully installed gymnasium-0.28.1 jax-jumpy-1.0.0
Requirement already satisfied: stable-baselines3[extra] in /usr/local/lib/python3.11/dist-packages (2.1.0)
Requirement already satisfied: gymnasium<0.30,>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (0.28.1)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (1.26.4)
Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (2.6.0+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (3.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (2.2.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (3.7.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (4.11.0.86)
Requirement already satisfied: pygame in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (2.18.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (7.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (4.67.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (14.0.0)
Collecting shimmy~=1.1.0 (from shimmy[atari]~=1.1.0; extra == "extra"->stable-baselines3[extra])
  Downloading Shimmy-1.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]) (11.2.1)
Collecting autorom~=0.6.1 (from autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra])
  Downloading AutoROM-0.6.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (8.2.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (2.32.4)
Collecting AutoROM.accept-rom-license (from autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra])
  Downloading AutoROM.accept-rom-license-0.6.1.tar.gz (434 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.7/434.7 kB 7.8 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: jax-jumpy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<0.30,>=0.28.1->stable-baselines3[extra]) (1.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<0.30,>=0.28.1->stable-baselines3[extra]) (4.14.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<0.30,>=0.28.1->stable-baselines3[extra]) (0.0.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.20->stable-baselines3[extra]) (2.4.1)
Collecting ale-py~=0.8.1 (from shimmy[atari]~=1.1.0; extra == "extra"->stable-baselines3[extra])
  Downloading ale_py-0.8.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.73.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.8.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (25.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.20.3)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (75.2.0)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.1.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (2025.5.1)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.13->stable-baselines3[extra])
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable-baselines3[extra]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.13->stable-baselines3[extra]) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (1.4.8)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3[extra]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->stable-baselines3[extra]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->stable-baselines3[extra]) (2025.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->stable-baselines3[extra]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->stable-baselines3[extra]) (2.19.2)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.11/dist-packages (from ale-py~=0.8.1->shimmy[atari]~=1.1.0; extra == "extra"->stable-baselines3[extra]) (6.5.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->stable-baselines3[extra]) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->stable-baselines3[extra]) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.20->stable-baselines3[extra]) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.20->stable-baselines3[extra]) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.20->stable-baselines3[extra]) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.20->stable-baselines3[extra]) (2024.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->autorom~=0.6.1->autorom[accept-rom-license]~=0.6.1; extra == "extra"->stable-baselines3[extra]) (2025.6.15)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.20->stable-baselines3[extra]) (2024.2.0)
Downloading AutoROM-0.6.1-py3-none-any.whl (9.4 kB)
Downloading Shimmy-1.1.0-py3-none-any.whl (37 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 96.8 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 81.0 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 39.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.4 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.2 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 31.2 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 1.9 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 86.7 MB/s eta 0:00:00:00:0100:01
Downloading ale_py-0.8.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 60.2 MB/s eta 0:00:00
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... done
  Created wheel for AutoROM.accept-rom-license: filename=autorom_accept_rom_license-0.6.1-py3-none-any.whl size=446709 sha256=84938be360fb41c9c1c40fdb43c309a23122a95589c5c638cd08ca0beb7c8338

In [3]:
!pip install git+https://github.com/DLR-RM/stable-baselines3

Collecting git+https://github.com/DLR-RM/stable-baselines3
  Cloning https://github.com/DLR-RM/stable-baselines3 to /tmp/pip-req-build-gld2ywxt
  Running command git clone --filter=blob:none --quiet https://github.com/DLR-RM/stable-baselines3 /tmp/pip-req-build-gld2ywxt
  Resolved https://github.com/DLR-RM/stable-baselines3 to commit dd7f5bfe63631630463f2f9bcb4762e6c040de12
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gymnasium<1.3.0,>=0.29.1 (from stable_baselines3==2.7.1a0)
  Downloading gymnasium-1.2.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3==2.7.1a0) (1.26.4)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3==2.7.1a0) (2.6.0+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable_baselines3==2.7.1a0) (3.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from stable_baselines3==2.7.1a0) (2.2.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from stable_baselines3==2.7.1a0) (3.7.2)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3==2.7.1a0) (4.14.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3==2.7.1a0) (0.0.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (11.2.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3==2.7.1a0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3==2.7.1a0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3==2.7.1a0) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->stable_baselines3==2.7.1a0) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3.0,>=2.3->stable_baselines3==2.7.1a0) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy<3.0,>=1.20->stable_baselines3==2.7.1a0) (2024.2.0)
Downloading gymnasium-1.2.0-py3-none-any.whl (944 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 944.3/944.3 kB 14.6 MB/s eta 0:00:00a 0:00:01
Building wheels for collected packages: stable_baselines3
  Building wheel for stable_baselines3 (pyproject.toml) ... done
  Created wheel for stable_baselines3: filename=stable_baselines3-2.7.1a0-py3-none-any.whl size=187348 sha256=4f4440f59a5dd24e5f2d079a78a6acffce58dc4699090c1e19fb9c83b84bfd97
  Stored in directory: /tmp/pip-ephem-wheel-cache-harz4641/wheels/4e/50/0a/1b04f64886428aef488eca102d1c66b00f5218ca4ec32fa9e6
Successfully built stable_baselines3
Installing collected packages: gymnasium, stable_baselines3
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 0.28.1
    Uninstalling gymnasium-0.28.1:
      Successfully uninstalled gymnasium-0.28.1
  Attempting uninstall: stable_baselines3
    Found existing installation: stable-baselines3 2.1.0
    Uninstalling stable-baselines3-2.1.0:
      Successfully uninstalled stable-baselines3-2.1.0
Successfully installed gymnasium-1.2.0 stable_baselines3-2.7.1a0

In [5]:
pip install git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib

Collecting git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib
  Cloning https://github.com/Stable-Baselines-Team/stable-baselines3-contrib to /tmp/pip-req-build-vg0st49a
  Running command git clone --filter=blob:none --quiet https://github.com/Stable-Baselines-Team/stable-baselines3-contrib /tmp/pip-req-build-vg0st49a
  Resolved https://github.com/Stable-Baselines-Team/stable-baselines3-contrib to commit 33889dbb215b8992bf463551657b79241f4bccf8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: stable_baselines3<3.0,>=2.7.0 in /usr/local/lib/python3.11/dist-packages (from sb3_contrib==2.7.0) (2.7.1a0)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.2.0)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.26.4)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2.6.0+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2.2.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.7.2)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (4.14.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (0.0.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (11.2.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy<3.0,>=1.20->stable_baselines3<3.0,>=2.7.0->sb3_contrib==2.7.0) (2024.2.0)
Building wheels for collected packages: sb3_contrib
  Building wheel for sb3_contrib (pyproject.toml) ... done
  Created wheel for sb3_contrib: filename=sb3_contrib-2.7.0-py3-none-any.whl size=93173 sha256=44e93c5703e5fdf9cffc0f5825af7b8f026a22a51af3986d02f07d4076bfeba9
  Stored in directory: /tmp/pip-ephem-wheel-cache-7pr_36f2/wheels/f0/c6/aa/f7853333ad7a263ac541ccb1fff7a8ebcb1d94855318f2a49a
Successfully built sb3_contrib
Installing collected packages: sb3_contrib
Successfully installed sb3_contrib-2.7.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-o9js5eb0
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-o9js5eb0
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit fb2becacbf3c48249ce960f3ef60a862f8fc6707
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.8)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-soe993dc/elegantrl_71c8f2b9cb8145cc8a7ce3e905f6520a
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-soe993dc/elegantrl_71c8f2b9cb8145cc8a7ce3e905f6520a
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit b2ec84b19a82e6f18b781743d8bf37ca27134238
  Preparing metadata (setup.py) ... done
Collecting alpaca-py<0.38,>=0.37 (from finrl==0.3.8)
  Downloading alpaca_py-0.37.0-py3-none-any.whl.metadata (13 kB)
Collecting alpaca-trade-api<4,>=3 (from finrl==0.3.8)
  Downloading alpaca_trade_api-3.2.0-py3-none-any.whl.metadata (29 kB)
Collecting ccxt<4,>=3 (from finrl==0.3.8)
  Downloading ccxt-3.1.60-py2.py3-none-any.whl.metadata (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 4.0 MB/s eta 0:00:00
Collecting jqdatasdk<2,>=1 (from finrl==0.3.8)
  Downloading jqdatasdk-1.9.7-py3-none-any.whl.metadata (5.8 kB)
Collecting pandas-market-calendars<6,>=5 (from finrl==0.3.8)
  Downloading pandas_market_calendars-5.1.1-py3-none-any.whl.metadata (9.7 kB)
Collecting pyfolio-reloaded<0.10,>=0.9 (from finrl==0.3.8)
  Downloading pyfolio_reloaded-0.9.9-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pyportfolioopt<2,>=1 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.8) (1.5.6)
Requirement already satisfied: ray<3,>=2 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (2.47.1)
Requirement already satisfied: scikit-learn<2,>=1 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.8) (1.2.2)
Collecting selenium<5,>=4 (from finrl==0.3.8)
  Downloading selenium-4.34.2-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.7.1a0)
Collecting stockstats<0.6,>=0.5 (from finrl==0.3.8)
  Downloading stockstats-0.5.4-py2.py3-none-any.whl.metadata (26 kB)
Collecting webdriver-manager<5,>=4 (from finrl==0.3.8)
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting wrds<4,>=3 (from finrl==0.3.8)
  Downloading wrds-3.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: yfinance<0.3,>=0.2 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.8) (0.2.63)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (1.1.1)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.2.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.11.7)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.32.4)
Collecting sseclient-py<2.0.0,>=1.7.2 (from alpaca-py<0.38,>=0.37->finrl==0.3.8)
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (15.0.1)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (1.26.4)
Collecting urllib3<2,>1.24 (from alpaca-trade-api<4,>=3->finrl==0.3.8)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (1.8.0)
Collecting websockets>=10.4 (from alpaca-py<0.38,>=0.37->finrl==0.3.8)
  Downloading websockets-10.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting msgpack<2.0.0,>=1.0.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.8)
  Downloading msgpack-1.0.3.tar.gz (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 kB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (3.12.13)
Collecting PyYAML==6.0.1 (from alpaca-trade-api<4,>=3->finrl==0.3.8)
  Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting deprecation==2.1.0 (from alpaca-trade-api<4,>=3->finrl==0.3.8)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.8) (25.0)
Requirement already satisfied: setuptools>=60.9.0 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.8) (75.2.0)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.8) (2025.6.15)
Requirement already satisfied: cryptography>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.8) (44.0.3)
Collecting aiodns>=1.1.1 (from ccxt<4,>=3->finrl==0.3.8)
  Downloading aiodns-3.5.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: yarl>=1.7.2 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.8) (1.20.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.11/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (2.0.41)
Collecting pymysql>=0.7.6 (from jqdatasdk<2,>=1->finrl==0.3.8)
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Collecting thriftpy2!=0.5.1,>=0.3.9 (from jqdatasdk<2,>=1->finrl==0.3.8)
  Downloading thriftpy2-0.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.2 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from pandas-market-calendars<6,>=5->finrl==0.3.8) (2025.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from pandas-market-calendars<6,>=5->finrl==0.3.8) (2.9.0.post0)
Collecting exchange-calendars>=3.3 (from pandas-market-calendars<6,>=5->finrl==0.3.8)
  Downloading exchange_calendars-4.11-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.11/dist-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (7.34.0)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (3.7.2)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.11/dist-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (2025.2)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (1.15.3)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.12.2)
Collecting empyrical-reloaded>=0.5.9 (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8)
  Downloading empyrical_reloaded-0.5.12-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: cvxpy>=1.1.19 in /usr/local/lib/python3.11/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (1.6.6)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in /usr/local/lib/python3.11/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (2.0.14)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (5.24.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (8.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (3.18.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (4.24.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (3.20.3)
Collecting aiohttp_cors (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading aiohttp_cors-0.8.1-py3-none-any.whl.metadata (20 kB)
Collecting colorful (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading colorful-0.5.7-py2.py3-none-any.whl.metadata (16 kB)
Collecting py-spy>=0.2.0 (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading py_spy-0.4.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (510 bytes)
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (1.73.1)
Collecting opencensus (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading opencensus-0.11.4-py2.py3-none-any.whl.metadata (12 kB)
Collecting opentelemetry-sdk (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading opentelemetry_sdk-1.36.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-prometheus (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading opentelemetry_exporter_prometheus-0.57b0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading opentelemetry_proto-1.36.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: prometheus_client>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.22.1)
Requirement already satisfied: smart_open in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (7.1.0)
Collecting virtualenv!=20.21.1,>=20.0.24 (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading virtualenv-20.33.1-py3-none-any.whl.metadata (4.5 kB)
Collecting tensorboardX>=1.9 (from ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading tensorboardx-2.6.4-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pyarrow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (19.0.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (2025.5.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2,>=1->finrl==0.3.8) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2,>=1->finrl==0.3.8) (3.6.0)
INFO: pip is looking at multiple versions of selenium to determine which version is compatible with other requirements. This could take a while.
Collecting selenium<5,>=4 (from finrl==0.3.8)
  Downloading selenium-4.34.1-py3-none-any.whl.metadata (7.5 kB)
  Downloading selenium-4.34.0-py3-none-any.whl.metadata (7.5 kB)
  Downloading selenium-4.33.0-py3-none-any.whl.metadata (7.5 kB)
  Downloading selenium-4.32.0-py3-none-any.whl.metadata (7.5 kB)
Collecting trio~=0.17 (from selenium<5,>=4->finrl==0.3.8)
  Downloading trio-0.30.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium<5,>=4->finrl==0.3.8)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions~=4.9 in /usr/local/lib/python3.11/dist-packages (from selenium<5,>=4->finrl==0.3.8) (4.14.0)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (1.2.0)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.6.0+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.1.1)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (4.11.0.86)
Requirement already satisfied: pygame in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.18.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (7.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (4.67.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (14.0.0)
Collecting ale-py>=0.9.0 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8)
  Using cached ale_py-0.11.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (11.2.1)
Collecting python-dotenv (from webdriver-manager<5,>=4->finrl==0.3.8)
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Collecting packaging (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.8)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting psycopg2-binary<2.10,>=2.9 (from wrds<4,>=3->finrl==0.3.8)
  Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (4.3.8)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (3.18.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (0.11.4)
INFO: pip is looking at multiple versions of yfinance to determine which version is compatible with other requirements. This could take a while.
Collecting yfinance<0.3,>=0.2 (from finrl==0.3.8)
  Downloading yfinance-0.2.65-py2.py3-none-any.whl.metadata (5.8 kB)
  Downloading yfinance-0.2.64-py2.py3-none-any.whl.metadata (5.8 kB)
  Downloading yfinance-0.2.62-py2.py3-none-any.whl.metadata (5.8 kB)
  Downloading yfinance-0.2.61-py2.py3-none-any.whl.metadata (5.8 kB)
  Downloading yfinance-0.2.60-py2.py3-none-any.whl.metadata (5.8 kB)
  Downloading yfinance-0.2.59-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting protobuf!=3.19.5,>=3.15.3 (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8)
  Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting yfinance<0.3,>=0.2 (from finrl==0.3.8)
  Downloading yfinance-0.2.58-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting th (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8)
  Downloading th-0.4.1-py3-none-any.whl.metadata (3.4 kB)
Collecting pycares>=4.9.0 (from aiodns>=1.1.1->ccxt<4,>=3->finrl==0.3.8)
  Downloading pycares-4.10.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (0.3.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl==0.3.8) (2.7)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl==0.3.8) (1.17.1)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (1.0.4)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (3.2.7.post2)
Requirement already satisfied: bottleneck>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from empyrical-reloaded>=0.5.9->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (1.4.2)
Collecting peewee>=3.16.2 (from yfinance<0.3,>=0.2->finrl==0.3.8)
  Downloading peewee-3.17.3.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 42.3 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyluach (from exchange-calendars>=3.3->pandas-market-calendars<6,>=5->finrl==0.3.8)
  Downloading pyluach-2.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.11/dist-packages (from exchange-calendars>=3.3->pandas-market-calendars<6,>=5->finrl==0.3.8) (1.0.0)
Collecting korean_lunar_calendar (from exchange-calendars>=3.3->pandas-market-calendars<6,>=5->finrl==0.3.8)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (0.0.4)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (4.4.2)

In [6]:
import yfinance as yf
import pandas as pd
import numpy as np
import ta
from ta import add_all_ta_features
from ta.trend import SMAIndicator, EMAIndicator, MACD, CCIIndicator, ADXIndicator
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.volatility import BollingerBands, AverageTrueRange
from ta.volume import OnBalanceVolumeIndicator
from ta.utils import dropna
import itertools

In [9]:
from __future__ import annotations

from typing import List

import gymnasium as gym
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from gymnasium import spaces
from gymnasium.utils import seeding
from stable_baselines3.common.vec_env import DummyVecEnv

matplotlib.use("Agg")
%matplotlib inline

# from stable_baselines3.common.logger import Logger, KVWriter, CSVOutputFormat

In [10]:
# DRL models from Stable Baselines 3
import statistics
import time

import numpy as np
import pandas as pd
from stable_baselines3 import A2C
from stable_baselines3 import DDPG
from stable_baselines3 import PPO
from stable_baselines3 import SAC
from stable_baselines3 import TD3
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.callbacks import CallbackList
from stable_baselines3.common.noise import NormalActionNoise
from stable_baselines3.common.noise import OrnsteinUhlenbeckActionNoise
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.logger import configure

In [11]:
from pypfopt import expected_returns, risk_models
from pypfopt import EfficientFrontier
from scipy.stats import skew, kurtosis

In [56]:
import random
import wandb
from wandb.integration.sb3 import WandbCallback

In [154]:
!wandb login --relogin 320a98c6a9ba9e09b5d88d9b64059d763ae265f4

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

In [91]:
DOW_30_TICKER = [
    "AXP",
    "AMGN",
    "AAPL",
    "BA",
    "CAT",
    "CSCO",
    "CVX",
    "GS",
    "HD",
    "HON",
    "IBM",
    "INTC",
    "JNJ",
    "KO",
    "JPM",
    "MCD",
    "MMM",
    "MRK",
    "MSFT",
    "NKE",
    "PG",
    "TRV",
    "UNH",
    "CRM",
    "VZ",
    "V",
    "WBA",
    "WMT",
    "DIS",
    "DOW",
]

INDICATORS_DOW_30 = [
    "sma_20", "sma_60", "ema_20",
    "rsi_14", "macd", "macd_signal",
    "boll_ub", "boll_lb", "boll_width",
    "atr_14", "obv", "vol_sma_20",
    "stoch_k", "stoch_d", "cci_14", "adx_14"
]

In [92]:
CRYPTO_TICKER = [

]

In [93]:
TRAIN_START_DATE = '2010-01-01'
TRADE_END_DATE = '2025-01-01'

In [94]:
def _adjust_prices(data_df: pd.DataFrame) -> pd.DataFrame:
    # use adjusted close price instead of close price
    data_df["adj"] = data_df["adjcp"] / data_df["close"]
    for col in ["open", "high", "low", "close"]:
        data_df[col] *= data_df["adj"]

    # drop the adjusted close price column
    return data_df.drop(["adjcp", "adj"], axis=1)

In [95]:
def get_data(dataset, start_date, end_date):
    if dataset == "DOW_30":
        """Fetches data from Yahoo API
        Returns
        -------
        `pd.DataFrame`
            7 columns: A date, open, high, low, close, volume and tick symbol
            for the specified stock ticker
        """
        # Download and save the data in a pandas DataFrame:
        data_df = pd.DataFrame()
        num_failures = 0
        for tic in DOW_30_TICKER:
            temp_df = yf.download(
                tic,
                start=start_date,
                end=end_date,
                auto_adjust=False,
            )
            if temp_df.columns.nlevels != 1:
                temp_df.columns = temp_df.columns.droplevel(1)
            temp_df["tic"] = tic
            if len(temp_df) > 0:
                data_df = pd.concat([data_df, temp_df], axis=0)
            else:
                num_failures += 1
                
        if num_failures == len(DOW_30_TICKER):
            raise ValueError("no data is fetched.")

        # reset the index, we want to use numbers as index instead of dates
        data_df = data_df.reset_index()
        try:
            # convert the column names to standardized names
            data_df.rename(
                columns={
                    "Date": "date",
                    "Adj Close": "adjcp",
                    "Close": "close",
                    "High": "high",
                    "Low": "low",
                    "Volume": "volume",
                    "Open": "open",
                    "tic": "tic",
                },
                inplace=True,
            )

            data_df = _adjust_prices(data_df)
        except NotImplementedError:
            print("the features are not supported currently")
            
        # create day of the week column (monday = 0)
        data_df["day"] = data_df["date"].dt.dayofweek
                
        # drop missing data
        data_df = data_df.dropna()
        data_df = data_df.reset_index(drop=True)
        
        print("Shape of DataFrame: ", data_df.shape)
        # print("Display DataFrame: ", data_df.head())

        data_df = data_df.sort_values(by=["date", "tic"]).reset_index(drop=True)

        return data_df
    elif dataset == "XAU-G/USD":
        pass
    elif dataset == "Crypto":
        pass

In [96]:
def clean_data(data):
    df = data.copy()
    df = df.sort_values(["date", "tic"], ignore_index=True)
    df.index = df.date.factorize()[0]
    merged_closes = df.pivot_table(index="date", columns="tic", values="close")
    merged_closes = merged_closes.dropna(axis=1)
    tics = merged_closes.columns
    df = df[df.tic.isin(tics)]
    return df

In [97]:
def add_indicators(df, dataset):
    df = df.sort_values(['tic', 'date']).reset_index(drop=True)

    if dataset == "DOW_30":
        df_indicators = pd.DataFrame()
        
        for tic, group in df.groupby('tic'):
            group = group.copy()
            
            # Trend indicators
            group['sma_20'] = SMAIndicator(group['close'], window=20).sma_indicator()
            group['sma_60'] = SMAIndicator(group['close'], window=60).sma_indicator()
            group['ema_20'] = EMAIndicator(group['close'], window=20).ema_indicator()
            macd = MACD(group['close'])
            group['macd'] = macd.macd()
            group['macd_signal'] = macd.macd_signal()
        
            # Momentum indicators
            group['rsi_14'] = RSIIndicator(group['close'], window=14).rsi()
            stoch = StochasticOscillator(high=group['high'], low=group['low'], close=group['close'])
            group['stoch_k'] = stoch.stoch()
            group['stoch_d'] = stoch.stoch_signal()
            group['cci_14'] = CCIIndicator(group['high'], group['low'], group['close'], window=14).cci()
            group['adx_14'] = ADXIndicator(group['high'], group['low'], group['close'], window=14).adx()
        
            # Volatility indicators
            boll = BollingerBands(close=group['close'], window=20, window_dev=2)
            group['boll_ub'] = boll.bollinger_hband()
            group['boll_lb'] = boll.bollinger_lband()
            group['boll_width'] = group['boll_ub'] - group['boll_lb']
            group['atr_14'] = AverageTrueRange(group['high'], group['low'], group['close'], window=14).average_true_range()
            
            # Volume indicators
            group['obv'] = OnBalanceVolumeIndicator(group['close'], group['volume']).on_balance_volume()
            group['vol_sma_20'] = group['volume'].rolling(window=20).mean()
        
            # Append
            df_indicators = pd.concat([df_indicators, group], axis=0)
        
        # Final sorting and cleanup
        df_indicators = df_indicators.replace([np.inf, -np.inf], np.nan).dropna()
        df_indicators = df_indicators.sort_values(['tic', 'date']).reset_index(drop=True)

        return df_indicators
    elif dataset == "XAU-G/USD":
        pass
    elif dataset == "Crypto":
        pass

In [98]:
def add_vix(data):
    """
    Add VIX data from Yahoo Finance using yfinance.
    
    :param data: (pd.DataFrame) Must have a 'date' column (datetime or string).
    :return: (pd.DataFrame) Original dataframe with 'vix' column added.
    """
    df = data.copy()

    # Ensure 'date' is datetime
    df["date"] = pd.to_datetime(df["date"])

    # Download VIX data
    vix_df = yf.download(
        "^VIX",
        start=df["date"].min().strftime("%Y-%m-%d"),
        end=(df["date"].max() + pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
        progress=False
    )

    # Reset index to get 'Date' as a column
    vix_df = vix_df.reset_index()[["Date", "Close"]]
    vix_df.columns = ["date", "vix"]

    # Merge with original dataframe
    df = df.merge(vix_df, on="date", how="left")

    # Sort
    df = df.sort_values(["date", "tic"]).reset_index(drop=True)

    return df

In [99]:
def calculate_turbulence(data):
    """calculate turbulence index based on dow 30"""
    # can add other market assets
    df = data.copy()
    df_price_pivot = df.pivot(index="date", columns="tic", values="close")
    # use returns to calculate turbulence
    df_price_pivot = df_price_pivot.pct_change()

    unique_date = df.date.unique()
    # start after a year
    start = 252
    turbulence_index = [0] * start
    # turbulence_index = [0]
    count = 0
    for i in range(start, len(unique_date)):
        current_price = df_price_pivot[df_price_pivot.index == unique_date[i]]
        # use one year rolling window to calcualte covariance
        hist_price = df_price_pivot[
            (df_price_pivot.index < unique_date[i])
            & (df_price_pivot.index >= unique_date[i - 252])
        ]
        # Drop tickers which has number missing values more than the "oldest" ticker
        filtered_hist_price = hist_price.iloc[
            hist_price.isna().sum().min() :
        ].dropna(axis=1)

        cov_temp = filtered_hist_price.cov()
        current_temp = current_price[[x for x in filtered_hist_price]] - np.mean(
            filtered_hist_price, axis=0
        )
        # cov_temp = hist_price.cov()
        # current_temp=(current_price - np.mean(hist_price,axis=0))

        temp = current_temp.values.dot(np.linalg.pinv(cov_temp)).dot(
            current_temp.values.T
        )
        if temp > 0:
            count += 1
            if count > 2:
                turbulence_temp = temp[0][0]
            else:
                # avoid large outlier because of the calculation just begins
                turbulence_temp = 0
        else:
            turbulence_temp = 0
        turbulence_index.append(turbulence_temp)
    try:
        turbulence_index = pd.DataFrame(
            {"date": df_price_pivot.index, "turbulence": turbulence_index}
        )
    except ValueError:
        raise Exception("Turbulence information could not be added.")
    return turbulence_index

In [100]:
def add_turbulence(data):
    """
    add turbulence index from a precalcualted dataframe
    :param data: (df) pandas dataframe
    :return: (df) pandas dataframe
    """
    df = data.copy()
    turbulence_index = calculate_turbulence(df)
    df = df.merge(turbulence_index, on="date")
    df = df.sort_values(["date", "tic"]).reset_index(drop=True)
    return df

In [101]:
def data_split(df, start, end, target_date_col="date"):
    """
    split the dataset into training or testing using date
    :param data: (df) pandas dataframe, start, end
    :return: (df) pandas dataframe
    """
    data = df[(df[target_date_col] >= start) & (df[target_date_col] < end)]
    data = data.sort_values([target_date_col, "tic"], ignore_index=True)
    data.index = data[target_date_col].factorize()[0]
    return data

In [102]:
class StockTradingEnv(gym.Env):
    """
    A stock trading environment for OpenAI gym

    Parameters:
        df (pandas.DataFrame): Dataframe containing data
        hmax (int): Maximum cash to be traded in each trade per asset.
        initial_amount (int): Amount of cash initially available
        buy_cost_pct (float, array): Cost for buying shares, each index corresponds to each asset
        sell_cost_pct (float, array): Cost for selling shares, each index corresponds to each asset
        turbulence_threshold (float): Maximum turbulence allowed in market for purchases to occur. If exceeded, positions are liquidated
        print_verbosity(int): When iterating (step), how often to print stats about state of env
    """

    metadata = {"render.modes": ["human"]}

    def __init__(
        self,
        df: pd.DataFrame,
        stock_dim: int,
        hmax: int,
        initial_amount: int,
        num_stock_shares: list[int],
        buy_cost_pct: list[float],
        sell_cost_pct: list[float],
        reward_scaling: float,
        state_space: int,
        action_space: int,
        tech_indicator_list: list[str],
        turbulence_threshold=None,
        risk_indicator_col="turbulence",
        make_plots: bool = False,
        print_verbosity=10,
        day=0,
        initial=True,
        previous_state=[],
        model_name="",
        mode="",
        iteration="",
    ):
        self.day = day
        self.df = df
        self.stock_dim = stock_dim
        self.hmax = hmax
        self.num_stock_shares = num_stock_shares
        self.initial_amount = initial_amount  # get the initial cash
        self.buy_cost_pct = buy_cost_pct
        self.sell_cost_pct = sell_cost_pct
        self.reward_scaling = reward_scaling
        self.state_space = state_space
        self.action_space = action_space
        self.tech_indicator_list = tech_indicator_list
        self.action_space = spaces.Box(low=-1, high=1, shape=(self.action_space,))
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(self.state_space,)
        )
        self.data = self.df.loc[self.day, :]
        self.terminal = False
        self.make_plots = make_plots
        self.print_verbosity = print_verbosity
        self.turbulence_threshold = turbulence_threshold
        self.risk_indicator_col = risk_indicator_col
        self.initial = initial
        self.previous_state = previous_state
        self.model_name = model_name
        self.mode = mode
        self.iteration = iteration
        # initalize state
        self.state = self._initiate_state()

        # initialize reward
        self.reward = 0
        self.turbulence = 0
        self.cost = 0
        self.trades = 0
        self.episode = 0
        # memorize all the total balance change
        self.asset_memory = [
            self.initial_amount
            + np.sum(
                np.array(self.num_stock_shares)
                * np.array(self.state[1 : 1 + self.stock_dim])
            )
        ]  # the initial total asset is calculated by cash + sum (num_share_stock_i * price_stock_i)
        self.rewards_memory = []
        self.actions_memory = []
        self.state_memory = (
            []
        )  # we need sometimes to preserve the state in the middle of trading process
        self.date_memory = [self._get_date()]
        #         self.logger = Logger('results',[CSVOutputFormat])
        # self.reset()
        self._seed()

    def _sell_stock(self, index, action):
        def _do_sell_normal():
            if (
                self.state[index + 2 * self.stock_dim + 1] != True
            ):  # check if the stock is able to sell, for simlicity we just add it in techical index
                # if self.state[index + 1] > 0: # if we use price<0 to denote a stock is unable to trade in that day, the total asset calculation may be wrong for the price is unreasonable
                # Sell only if the price is > 0 (no missing data in this particular date)
                # perform sell action based on the sign of the action
                if self.state[index + self.stock_dim + 1] > 0:
                    # Sell only if current asset is > 0
                    sell_num_shares = min(
                        abs(action), self.state[index + self.stock_dim + 1]
                    )
                    sell_amount = (
                        self.state[index + 1]
                        * sell_num_shares
                        * (1 - self.sell_cost_pct[index])
                    )
                    # update balance
                    self.state[0] += sell_amount

                    self.state[index + self.stock_dim + 1] -= sell_num_shares
                    self.cost += (
                        self.state[index + 1]
                        * sell_num_shares
                        * self.sell_cost_pct[index]
                    )
                    self.trades += 1
                else:
                    sell_num_shares = 0
            else:
                sell_num_shares = 0

            return sell_num_shares

        # perform sell action based on the sign of the action
        if self.turbulence_threshold is not None:
            if self.turbulence >= self.turbulence_threshold:
                if self.state[index + 1] > 0:
                    # Sell only if the price is > 0 (no missing data in this particular date)
                    # if turbulence goes over threshold, just clear out all positions
                    if self.state[index + self.stock_dim + 1] > 0:
                        # Sell only if current asset is > 0
                        sell_num_shares = self.state[index + self.stock_dim + 1]
                        sell_amount = (
                            self.state[index + 1]
                            * sell_num_shares
                            * (1 - self.sell_cost_pct[index])
                        )
                        # update balance
                        self.state[0] += sell_amount
                        self.state[index + self.stock_dim + 1] = 0
                        self.cost += (
                            self.state[index + 1]
                            * sell_num_shares
                            * self.sell_cost_pct[index]
                        )
                        self.trades += 1
                    else:
                        sell_num_shares = 0
                else:
                    sell_num_shares = 0
            else:
                sell_num_shares = _do_sell_normal()
        else:
            sell_num_shares = _do_sell_normal()

        return sell_num_shares

    def _buy_stock(self, index, action):
        def _do_buy():
            if (
                self.state[index + 2 * self.stock_dim + 1] != True
            ):  # check if the stock is able to buy
                # if self.state[index + 1] >0:
                # Buy only if the price is > 0 (no missing data in this particular date)
                available_amount = self.state[0] // (
                    self.state[index + 1] * (1 + self.buy_cost_pct[index])
                )  # when buying stocks, we should consider the cost of trading when calculating available_amount, or we may be have cash<0
                # print('available_amount:{}'.format(available_amount))

                # update balance
                buy_num_shares = min(available_amount, action)
                buy_amount = (
                    self.state[index + 1]
                    * buy_num_shares
                    * (1 + self.buy_cost_pct[index])
                )
                self.state[0] -= buy_amount

                self.state[index + self.stock_dim + 1] += buy_num_shares

                self.cost += (
                    self.state[index + 1] * buy_num_shares * self.buy_cost_pct[index]
                )
                self.trades += 1
            else:
                buy_num_shares = 0

            return buy_num_shares

        # perform buy action based on the sign of the action
        if self.turbulence_threshold is None:
            buy_num_shares = _do_buy()
        else:
            if self.turbulence < self.turbulence_threshold:
                buy_num_shares = _do_buy()
            else:
                buy_num_shares = 0
                pass

        return buy_num_shares

    def _make_plot(self):
        plt.plot(self.asset_memory, "r")
        plt.savefig(f"results/account_value_trade_{self.episode}.png")
        plt.close()

    def step(self, actions):
        self.terminal = self.day >= len(self.df.index.unique()) - 1
        if self.terminal:
            # print(f"Episode: {self.episode}")
            if self.make_plots:
                self._make_plot()
            end_total_asset = self.state[0] + sum(
                np.array(self.state[1 : (self.stock_dim + 1)])
                * np.array(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
            )
            df_total_value = pd.DataFrame(self.asset_memory)
            tot_reward = (
                self.state[0]
                + sum(
                    np.array(self.state[1 : (self.stock_dim + 1)])
                    * np.array(
                        self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)]
                    )
                )
                - self.asset_memory[0]
            )  # initial_amount is only cash part of our initial asset
            df_total_value.columns = ["account_value"]
            df_total_value["date"] = self.date_memory
            df_total_value["daily_return"] = df_total_value["account_value"].pct_change(
                1
            )
            if df_total_value["daily_return"].std() != 0:
                sharpe = (
                    (252**0.5)
                    * df_total_value["daily_return"].mean()
                    / df_total_value["daily_return"].std()
                )
            df_rewards = pd.DataFrame(self.rewards_memory)
            df_rewards.columns = ["account_rewards"]
            df_rewards["date"] = self.date_memory[:-1]
            if self.episode % self.print_verbosity == 0:
                print(f"day: {self.day}, episode: {self.episode}")
                print(f"begin_total_asset: {self.asset_memory[0]:0.2f}")
                print(f"end_total_asset: {end_total_asset:0.2f}")
                print(f"total_reward: {tot_reward:0.2f}")
                print(f"total_cost: {self.cost:0.2f}")
                print(f"total_trades: {self.trades}")
                if df_total_value["daily_return"].std() != 0:
                    print(f"Sharpe: {sharpe:0.3f}")
                print("=================================")

            if (self.model_name != "") and (self.mode != ""):
                df_actions = self.save_action_memory()
                df_actions.to_csv(
                    "results/actions_{}_{}_{}.csv".format(
                        self.mode, self.model_name, self.iteration
                    )
                )
                df_total_value.to_csv(
                    "results/account_value_{}_{}_{}.csv".format(
                        self.mode, self.model_name, self.iteration
                    ),
                    index=False,
                )
                df_rewards.to_csv(
                    "results/account_rewards_{}_{}_{}.csv".format(
                        self.mode, self.model_name, self.iteration
                    ),
                    index=False,
                )
                plt.plot(self.asset_memory, "r")
                plt.savefig(
                    "results/account_value_{}_{}_{}.png".format(
                        self.mode, self.model_name, self.iteration
                    )
                )
                plt.close()

            # Add outputs to logger interface
            # logger.record("environment/portfolio_value", end_total_asset)
            # logger.record("environment/total_reward", tot_reward)
            # logger.record("environment/total_reward_pct", (tot_reward / (end_total_asset - tot_reward)) * 100)
            # logger.record("environment/total_cost", self.cost)
            # logger.record("environment/total_trades", self.trades)

            return self.state, self.reward, self.terminal, False, {}

        else:
            actions = actions * self.hmax  # actions initially is scaled between 0 to 1
            actions = actions.astype(
                int
            )  # convert into integer because we can't by fraction of shares
            if self.turbulence_threshold is not None:
                if self.turbulence >= self.turbulence_threshold:
                    actions = np.array([-self.hmax] * self.stock_dim)
            begin_total_asset = self.state[0] + sum(
                np.array(self.state[1 : (self.stock_dim + 1)])
                * np.array(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
            )
            # print("begin_total_asset:{}".format(begin_total_asset))

            argsort_actions = np.argsort(actions)
            sell_index = argsort_actions[: np.where(actions < 0)[0].shape[0]]
            buy_index = argsort_actions[::-1][: np.where(actions > 0)[0].shape[0]]

            for index in sell_index:
                # print(f"Num shares before: {self.state[index+self.stock_dim+1]}")
                # print(f'take sell action before : {actions[index]}')
                actions[index] = self._sell_stock(index, actions[index]) * (-1)
                # print(f'take sell action after : {actions[index]}')
                # print(f"Num shares after: {self.state[index+self.stock_dim+1]}")

            for index in buy_index:
                # print('take buy action: {}'.format(actions[index]))
                actions[index] = self._buy_stock(index, actions[index])

            self.actions_memory.append(actions)

            # state: s -> s+1
            self.day += 1
            self.data = self.df.loc[self.day, :]
            if self.turbulence_threshold is not None:
                if len(self.df.tic.unique()) == 1:
                    self.turbulence = self.data[self.risk_indicator_col]
                elif len(self.df.tic.unique()) > 1:
                    self.turbulence = self.data[self.risk_indicator_col].values[0]
            self.state = self._update_state()

            end_total_asset = self.state[0] + sum(
                np.array(self.state[1 : (self.stock_dim + 1)])
                * np.array(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
            )
            self.asset_memory.append(end_total_asset)
            self.date_memory.append(self._get_date())
            self.reward = end_total_asset - begin_total_asset
            self.rewards_memory.append(self.reward)
            self.reward = self.reward * self.reward_scaling
            self.state_memory.append(
                self.state
            )  # add current state in state_recorder for each step

        return self.state, self.reward, self.terminal, False, {}

    def reset(
        self,
        *,
        seed=None,
        options=None,
    ):
        # initiate state
        self.day = 0
        self.data = self.df.loc[self.day, :]
        self.state = self._initiate_state()

        if self.initial:
            self.asset_memory = [
                self.initial_amount
                + np.sum(
                    np.array(self.num_stock_shares)
                    * np.array(self.state[1 : 1 + self.stock_dim])
                )
            ]
        else:
            previous_total_asset = self.previous_state[0] + sum(
                np.array(self.state[1 : (self.stock_dim + 1)])
                * np.array(
                    self.previous_state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)]
                )
            )
            self.asset_memory = [previous_total_asset]

        self.turbulence = 0
        self.cost = 0
        self.trades = 0
        self.terminal = False
        # self.iteration=self.iteration
        self.rewards_memory = []
        self.actions_memory = []
        self.date_memory = [self._get_date()]

        self.episode += 1

        return self.state, {}

    def render(self, mode="human", close=False):
        return self.state

    def _initiate_state(self):
        if self.initial:
            # For Initial State
            if len(self.df.tic.unique()) > 1:
                # for multiple stock
                state = (
                    [self.initial_amount]
                    + self.data.close.values.tolist()
                    + self.num_stock_shares
                    + sum(
                        (
                            self.data[tech].values.tolist()
                            for tech in self.tech_indicator_list
                        ),
                        [],
                    )
                )  # append initial stocks_share to initial state, instead of all zero
            else:
                # for single stock
                state = (
                    [self.initial_amount]
                    + [self.data.close]
                    + [0] * self.stock_dim
                    + sum(([self.data[tech]] for tech in self.tech_indicator_list), [])
                )
        else:
            # Using Previous State
            if len(self.df.tic.unique()) > 1:
                # for multiple stock
                state = (
                    [self.previous_state[0]]
                    + self.data.close.values.tolist()
                    + self.previous_state[
                        (self.stock_dim + 1) : (self.stock_dim * 2 + 1)
                    ]
                    + sum(
                        (
                            self.data[tech].values.tolist()
                            for tech in self.tech_indicator_list
                        ),
                        [],
                    )
                )
            else:
                # for single stock
                state = (
                    [self.previous_state[0]]
                    + [self.data.close]
                    + self.previous_state[
                        (self.stock_dim + 1) : (self.stock_dim * 2 + 1)
                    ]
                    + sum(([self.data[tech]] for tech in self.tech_indicator_list), [])
                )
        return state

    def _update_state(self):
        if len(self.df.tic.unique()) > 1:
            # for multiple stock
            state = (
                [self.state[0]]
                + self.data.close.values.tolist()
                + list(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
                + sum(
                    (
                        self.data[tech].values.tolist()
                        for tech in self.tech_indicator_list
                    ),
                    [],
                )
            )

        else:
            # for single stock
            state = (
                [self.state[0]]
                + [self.data.close]
                + list(self.state[(self.stock_dim + 1) : (self.stock_dim * 2 + 1)])
                + sum(([self.data[tech]] for tech in self.tech_indicator_list), [])
            )

        return state

    def _get_date(self):
        if len(self.df.tic.unique()) > 1:
            date = self.data.date.unique()[0]
        else:
            date = self.data.date
        return date

    # add save_state_memory to preserve state in the trading process
    def save_state_memory(self):
        if len(self.df.tic.unique()) > 1:
            # date and close price length must match actions length
            date_list = self.date_memory[:-1]
            df_date = pd.DataFrame(date_list)
            df_date.columns = ["date"]

            state_list = self.state_memory
            df_states = pd.DataFrame(
                state_list,
                columns=[
                    "cash",
                    "Bitcoin_price",
                    "Gold_price",
                    "Bitcoin_num",
                    "Gold_num",
                    "Bitcoin_Disable",
                    "Gold_Disable",
                ],
            )
            df_states.index = df_date.date
            # df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        else:
            date_list = self.date_memory[:-1]
            state_list = self.state_memory
            df_states = pd.DataFrame({"date": date_list, "states": state_list})
        # print(df_states)
        return df_states

    def save_asset_memory(self):
        date_list = self.date_memory
        asset_list = self.asset_memory
        # print(len(date_list))
        # print(len(asset_list))
        df_account_value = pd.DataFrame(
            {"date": date_list, "account_value": asset_list}
        )
        return df_account_value

    def save_action_memory(self):
        if len(self.df.tic.unique()) > 1:
            # date and close price length must match actions length
            date_list = self.date_memory[:-1]
            df_date = pd.DataFrame(date_list)
            df_date.columns = ["date"]

            action_list = self.actions_memory
            df_actions = pd.DataFrame(action_list)
            df_actions.columns = self.data.tic.values
            df_actions.index = df_date.date
            # df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        else:
            date_list = self.date_memory[:-1]
            action_list = self.actions_memory
            df_actions = pd.DataFrame({"date": date_list, "actions": action_list})
        return df_actions

    def _seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def get_sb_env(self):
        e = DummyVecEnv([lambda: self])
        obs = e.reset()
        return e, obs

In [103]:
from sb3_contrib import RecurrentPPO
from sb3_contrib import CrossQ
from sb3_contrib import TRPO

In [104]:
A2C_PARAMS = {
    "n_steps": 5,
    "gamma": 0.995,            # Slightly higher for finance
    "learning_rate": 5e-4,     # Lower for stability
    "ent_coef": 0.01,          # Exploration without over-randomizing
    "vf_coef": 0.25,
    "max_grad_norm": 0.5,
    "gae_lambda": 1.0,
}

PPO_PARAMS = {
    "n_steps": 2048,
    "batch_size": 256,         # Bigger batches = more stability
    "gamma": 0.995,
    "learning_rate": 2.5e-4,
    "ent_coef": 0.01,          # 0.1 is too high for finance
    "clip_range": 0.2,
    "n_epochs": 10,
    "gae_lambda": 0.95,
    "max_grad_norm": 0.5,
}

TD3_PARAMS = {
    "batch_size": 256,         # Bigger batch size for finance
    "buffer_size": 1_000_000,
    "learning_rate": 3e-4,
    "gamma": 0.995,
    "tau": 0.005,
    "policy_delay": 2,
    "train_freq": (1, "step"),
}

SAC_PARAMS = {
    "batch_size": 256,
    "buffer_size": 1_000_000,
    "learning_rate": 3e-4,
    "learning_starts": 10_000,
    "gamma": 0.995,
    "tau": 0.005,
    "ent_coef": "auto",
}

TRPO_PARAMS = {
    "n_steps": 2048,
    "batch_size": 256,
    "gamma": 0.995,
    "learning_rate": 1e-4,
    "ent_coef": 0.0,
    "gae_lambda": 0.95,
    "max_kl": 0.01,
    "cg_max_steps": 10,
    "cg_damping": 0.1,
    "vf_coef": 0.5,
}

RECCURENT_PPO_PARAMS = {
    "learning_rate": 3e-4,
    "n_steps": 128,
    "batch_size": 128,
    "n_epochs": 10,
    "gamma": 0.995,
    "gae_lambda": 0.95,
    "clip_range": 0.2,
    "ent_coef": 0.005,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "use_sde": False,
}


CROSSQ_PARAMS = {
    "learning_rate": 3e-4,
    "buffer_size": 1_000_000,
    "learning_starts": 1000,
    "batch_size": 256,
    "gamma": 0.995,
    "train_freq": 1,
    "gradient_steps": 1,
    "n_steps": 1,
    "ent_coef": "auto",
    "target_entropy": "auto",
    "policy_delay": 2,
}

In [105]:
DEFAULT_PARAMS = {
    "a2c": A2C_PARAMS,
    "ppo": PPO_PARAMS,
    "trpo": TRPO_PARAMS,
    "td3": TD3_PARAMS,
    "sac": SAC_PARAMS,
    "rppo": RECCURENT_PPO_PARAMS,
    "crossq": CROSSQ_PARAMS,
}

In [106]:
MODELS = {"a2c": A2C, "td3": TD3, "sac": SAC, "ppo": PPO, "rppo": RecurrentPPO, "crossq": CrossQ, "trpo": TRPO}

In [107]:
NOISE = {
    "normal": NormalActionNoise,
    "ornstein_uhlenbeck": OrnsteinUhlenbeckActionNoise,
}

In [108]:
class TensorboardCallback(BaseCallback):
    """
    More complete TensorBoard logging callback for SB3 models.
    Logs rewards, episode lengths, rollout stats, policy/value losses,
    learning rates, FPS, action statistics, and more.

    Works with algorithms like PPO, A2C, SAC, TD3, DDPG.
    """

    def __init__(self, verbose=0, track_actions=True):
        super().__init__(verbose)
        self.episode_rewards = []
        self.episode_lengths = []
        self.current_episode_reward = 0
        self.current_episode_length = 0
        self.start_time = None
        self.track_actions = track_actions
        self.actions_buffer = []

    def _on_training_start(self) -> None:
        self.start_time = time.time()
        self.logger.record("time/training_start", self.start_time)

    def _on_step(self) -> bool:
        try:
            reward = self.locals.get("rewards", None) or self.locals.get("reward", None)
            if reward is not None:
                reward_val = reward[0] if isinstance(reward, (list, np.ndarray)) else reward
                self.current_episode_reward += reward_val
                self.current_episode_length += 1
                self.logger.record("train/step_reward", reward_val)

            if self.track_actions and "actions" in self.locals:
                act = self.locals["actions"]
                if isinstance(act, (list, np.ndarray)):
                    self.actions_buffer.append(np.array(act).flatten())
                else:
                    self.actions_buffer.append([act])
        except Exception as e:
            if self.verbose:
                print(f"[Warning] Step logging error: {e}")

        # Episode finished?
        done = self.locals.get("dones", [False])[0] or self.locals.get("done", False)
        if done:
            self.episode_rewards.append(self.current_episode_reward)
            self.episode_lengths.append(self.current_episode_length)

            self.logger.record("train/episode_reward", self.current_episode_reward)
            self.logger.record("train/episode_length", self.current_episode_length)

            if len(self.episode_rewards) >= 5:
                self.logger.record("train/episode_reward_mean_5", np.mean(self.episode_rewards[-5:]))

            self.current_episode_reward = 0
            self.current_episode_length = 0
            self.actions_buffer.clear()

        return True

    def _on_rollout_end(self) -> None:
        try:
            rb_rewards = self.locals["rollout_buffer"].rewards.flatten()
            self.logger.record("train/rollout_reward_min", float(np.min(rb_rewards)))
            self.logger.record("train/rollout_reward_mean", float(np.mean(rb_rewards)))
            self.logger.record("train/rollout_reward_max", float(np.max(rb_rewards)))
        except Exception:
            pass

        # Log action statistics
        if self.track_actions and len(self.actions_buffer) > 0:
            acts = np.concatenate(self.actions_buffer)
            self.logger.record("actions/mean", float(np.mean(acts)))
            self.logger.record("actions/std", float(np.std(acts)))
            self.logger.record("actions/min", float(np.min(acts)))
            self.logger.record("actions/max", float(np.max(acts)))

        # Log learning rate
        try:
            if hasattr(self.model, "lr_schedule"):
                lr = self.model.lr_schedule(self.model._current_progress_remaining)
            elif hasattr(self.model, "learning_rate"):
                lr = self.model.learning_rate
            else:
                lr = None
            if lr is not None:
                self.logger.record("train/learning_rate", float(lr))
        except Exception:
            pass

        # Try logging loss metrics if available
        try:
            if hasattr(self.model, "logger"):
                # PPO, A2C, etc. log losses internally, but we can add tags here if needed
                pass
        except Exception:
            pass

    def _on_training_end(self) -> None:
        total_time = time.time() - self.start_time
        self.logger.record("time/training_end", time.time())
        self.logger.record("time/total_training_time_sec", total_time)
        if self.verbose:
            print(f"Training finished in {total_time:.2f} seconds.")

In [109]:
class DRLAgent:
    """Provides implementations for DRL algorithms

    Attributes
    ----------
        env: gym environment class
            user-defined class

    Methods
    -------
        get_model()
            setup DRL algorithms
        train_model()
            train DRL algorithms in a train dataset
            and output the trained model
        DRL_prediction()
            make a prediction in a test dataset and get results
    """

    def __init__(self, env):
        self.env = env

    def get_model(
        self,
        model_name,
        policy="MlpPolicy",
        policy_kwargs=None,
        model_kwargs=None,
        verbose=1,
        seed=None,
        tensorboard_log=None,
    ):
        if model_name not in MODELS:
            raise ValueError(
                f"Model '{model_name}' not found in MODELS."
            )  # this is more informative than NotImplementedError("NotImplementedError")

        model_kwargs = DEFAULT_PARAMS[model_name]

        if "action_noise" in model_kwargs:
            n_actions = self.env.action_space.shape[-1]
            model_kwargs["action_noise"] = NOISE[model_kwargs["action_noise"]](
                mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)
            )
        print(model_kwargs)
        return MODELS[model_name](
            policy=policy,
            env=self.env,
            tensorboard_log=tensorboard_log,
            verbose=verbose,
            policy_kwargs=policy_kwargs,
            seed=seed,
            **model_kwargs,
        )

    @staticmethod
    def train_model(
        model,
        tb_log_name,
        total_timesteps=5000,
        callbacks: Optional[List[BaseCallback]] = None,
    ):  # this function is static method, so it can be called without creating an instance of the class

        all_callbacks = [TensorboardCallback()]
        if callbacks:
            all_callbacks += callbacks

        model = model.learn(
            total_timesteps=total_timesteps,
            tb_log_name=tb_log_name,
            callback=(
                CallbackList(
                    all_callbacks
                )
            ),
        )
        return model

    @staticmethod
    def DRL_prediction(model, environment, deterministic=True):
        """make a prediction and get results"""
        test_env, test_obs = environment.get_sb_env()
        account_memory = None  # This help avoid unnecessary list creation
        actions_memory = None  # optimize memory consumption
        # state_memory=[] #add memory pool to store states

        test_env.reset()
        max_steps = len(environment.df.index.unique()) - 1

        for i in range(len(environment.df.index.unique())):
            action, _states = model.predict(test_obs, deterministic=deterministic)
            # account_memory = test_env.env_method(method_name="save_asset_memory")
            # actions_memory = test_env.env_method(method_name="save_action_memory")
            test_obs, rewards, dones, info = test_env.step(action)

            if (
                i == max_steps - 1
            ):  # more descriptive condition for early termination to clarify the logic
                account_memory = test_env.env_method(method_name="save_asset_memory")
                actions_memory = test_env.env_method(method_name="save_action_memory")
            # add current state to state memory
            # state_memory=test_env.env_method(method_name="save_state_memory")

            if dones[0]:
                print("hit end!")
                break
        return account_memory[0], actions_memory[0]

In [110]:
def build_mvo_and_baselines(train_df, trade_price_df, initial_capital=1_000_000, weight_bounds=(0,0.5)):
    """
    train_df: raw rows with columns ['date','tic','close'] used to compute mu/cov
    trade_price_df: pivoted index=date, columns=tic with prices (out-of-sample period)
    """
    price_train = train_df.pivot(index='date', columns='tic', values='close').sort_index()
    price_train.index = pd.to_datetime(price_train.index)
    # compute daily returns
    returns_train = price_train.pct_change().dropna()

    # try pypfopt
    try:
        mu = expected_returns.mean_historical_return(price_train)  # annualized mu
        S = risk_models.sample_cov(price_train)
        ef = EfficientFrontier(mu, S, weight_bounds=weight_bounds)
        ef.max_sharpe()
        weights = ef.clean_weights()
        print("MVO weights from PyPortfolioOpt")
    except Exception as e:
        print("pypfopt not available or failed:", e)
        # fallback to equal weight
        cols = price_train.columns.tolist()
        weights = {c: 1/len(cols) for c in cols}
        print("Using equal-weight fallback")

    # prepare weights aligned with trade_price_df columns
    w_arr = np.array([weights.get(t, 0.0) for t in trade_price_df.columns])

    # compute shares from last available price in trade_price_df
    last_prices = trade_price_df.iloc[-1].to_numpy()
    dollar_alloc = w_arr * initial_capital
    # avoid divide by zero
    shares = np.where(last_prices > 0, dollar_alloc / last_prices, 0.0)

    # portfolio value time series
    portfolio_values = (trade_price_df.values * shares).sum(axis=1)
    df_mvo = pd.DataFrame({'date': trade_price_df.index, 'account_value': portfolio_values})
    # also build equal-weight and buy-and-hold for comparison
    # equal weight: allocate equally across available assets
    n = trade_price_df.shape[1]
    ew_shares = np.where(last_prices > 0, (initial_capital / n) / last_prices, 0.0)
    port_ew = (trade_price_df.values * ew_shares).sum(axis=1)
    df_ew = pd.DataFrame({'date': trade_price_df.index, 'account_value': port_ew})
    # buy-and-hold benchmark on index: simply sum shares of each asset with equal weight buying at first trade price
    bh_shares = np.where(trade_price_df.iloc[0].to_numpy() > 0, (initial_capital / n) / trade_price_df.iloc[0].to_numpy(), 0.0)
    port_bh = (trade_price_df.values * bh_shares).sum(axis=1)
    df_bh = pd.DataFrame({'date': trade_price_df.index, 'account_value': port_bh})

    return df_mvo, df_ew, df_bh, weights

In [111]:
def calculate_metrics(
    df_account_value, 
    initial_amount=1_000_000,
    risk_free_rate=0.0
):
    """
    Calculate period, return, risk & risk-adjusted metrics from equity curve.
    
    Params:
    - df_account_value: pd.DataFrame with 'account_value' and datetime index or 'date' col
    - initial_amount: starting capital
    - risk_free_rate: daily risk-free rate, default 0.0
    
    Returns: dict of all metrics
    """
    
    # Prepare DataFrame
    if 'date' in df_account_value.columns:
        df = df_account_value.copy()
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date').reset_index(drop=True)
        df.set_index('date', inplace=True)
    else:
        df = df_account_value.copy()
        df.index = pd.to_datetime(df.index)
        df = df.sort_index()

    start_date = df.index[0]
    end_date = df.index[-1]
    duration_days = (end_date - start_date).days

    start_value = df['account_value'].iloc[0]
    end_value = df['account_value'].iloc[-1]

    cum_return = (end_value / start_value - 1) * 100
    years = duration_days / 365.25
    cagr = ((end_value / start_value) ** (1 / years) - 1) * 100 if years > 0 else np.nan
    annualized_return = cagr

    # Daily returns
    df['returns'] = df['account_value'].pct_change().fillna(0)

    # Annualized Volatility
    daily_vol = df['returns'].std()
    ann_vol = daily_vol * np.sqrt(252) * 100

    # Drawdowns
    running_max = df['account_value'].cummax()
    drawdowns = (df['account_value'] - running_max) / running_max
    max_drawdown = drawdowns.min() * 100

    # Drawdown durations
    dd_durations = []
    duration = 0
    in_dd = False
    for dd in drawdowns:
        if dd < 0:
            duration += 1
            in_dd = True
        else:
            if in_dd:
                dd_durations.append(duration)
            duration = 0
            in_dd = False
    if in_dd:
        dd_durations.append(duration)
    max_dd_duration = max(dd_durations) if dd_durations else 0
    avg_dd_duration = np.mean(dd_durations) if dd_durations else 0

    avg_drawdown = drawdowns[drawdowns < 0].mean() * 100 if any(drawdowns < 0) else 0

    # Skewness & Kurtosis
    ret_skew = skew(df['returns'])
    ret_kurt = kurtosis(df['returns'])

    # VaR & CVaR 95%
    var_95 = np.percentile(df['returns'], 5) * 100
    cvar_95 = df['returns'][df['returns'] <= var_95/100].mean() * 100 if len(df['returns'][df['returns'] <= var_95/100]) > 0 else np.nan

    # Risk-adjusted returns

    # Excess returns over risk-free
    excess_returns = df['returns'] - risk_free_rate

    # Sharpe Ratio
    sharpe_ratio = (excess_returns.mean() / excess_returns.std()) * np.sqrt(252) if excess_returns.std() != 0 else np.nan

    # Sortino Ratio (downside deviation)
    downside_returns = excess_returns[excess_returns < 0]
    downside_std = downside_returns.std()
    sortino_ratio = (excess_returns.mean() / downside_std) * np.sqrt(252) if downside_std != 0 else np.nan

    # Calmar Ratio (Annualized Return / Max Drawdown absolute)
    calmar_ratio = annualized_return / abs(max_drawdown) if max_drawdown != 0 else np.nan

    return {
        'Start': start_date,
        'End': end_date,
        'Duration (days)': duration_days,
        'Cumulative Return [%]': cum_return,
        'Annualized Return [%]': annualized_return,
        'CAGR [%]': cagr,
        'Annualized Volatility [%]': ann_vol,
        'Max Drawdown [%]': max_drawdown,
        'Max Drawdown Duration (days)': max_dd_duration,
        'Average Drawdown [%]': avg_drawdown,
        'Average Drawdown Duration (days)': avg_dd_duration,
        'Skewness': ret_skew,
        'Kurtosis': ret_kurt,
        'VaR 95%': var_95,
        'CVaR 95%': cvar_95,
        'Sharpe Ratio': sharpe_ratio,
        'Sortino Ratio': sortino_ratio,
        'Calmar Ratio': calmar_ratio,
    }

In [112]:
def extract_trades_from_positions(df_actions, df_prices):
    """
    df_actions: daily positions for each ticker (index=date, columns=tickers)
    df_prices: daily close prices for tickers (index=date, columns=tickers)
    
    Returns DataFrame with columns:
    ['tic', 'entry_date', 'exit_date', 'entry_price', 'exit_price']
    """

    trades = []
    for tic in df_actions.columns:
        positions = df_actions[tic]
        prices = df_prices[tic]
        
        position = 0
        entry_date = None
        entry_price = None
        
        for date, pos in positions.items():
            price = prices.loc[date]
            
            # Entry: position changes from 0 to positive
            if position == 0 and pos > 0:
                position = pos
                entry_date = date
                entry_price = price
            
            # Exit: position changes from positive to 0 (or smaller)
            elif position > 0 and pos == 0:
                exit_date = date
                exit_price = price
                
                trades.append({
                    'tic': tic,
                    'entry_date': entry_date,
                    'exit_date': exit_date,
                    'entry_price': entry_price,
                    'exit_price': exit_price,
                })
                
                position = 0
                entry_date = None
                entry_price = None
            
            # (Optional) handle partial exits / position changes — requires more logic
            
    trades_df = pd.DataFrame(trades)
    return trades_df

In [113]:
def calculate_trade_metrics(trades_df):
    """
    trades_df must have columns:
    - 'entry_date' (datetime)
    - 'exit_date' (datetime)
    - 'entry_price'
    - 'exit_price'
    - Optionally 'quantity' or 'position_size'
    
    Returns dict of trade-level metrics.
    """

    if trades_df.empty:
        # No trades, return NaN for all
        nan = np.nan
        return {
            'Number of Trades': 0,
            'Win Rate [%]': nan,
            'Best Trade [%]': nan,
            'Worst Trade [%]': nan,
            'Average Trade [%]': nan,
            'Max Trade Duration (days)': nan,
            'Average Trade Duration (days)': nan,
            'Profit Factor': nan,
            'Expectancy [%]': nan,
            'SQN': nan,
            'Kelly Criterion': nan,
        }
    
    # Calculate trade returns (%)
    trades_df = trades_df.copy()
    trades_df['trade_return'] = (trades_df['exit_price'] - trades_df['entry_price']) / trades_df['entry_price'] * 100

    # Trade durations in days
    trades_df['entry_date'] = pd.to_datetime(trades_df['entry_date'])
    trades_df['exit_date'] = pd.to_datetime(trades_df['exit_date'])
    trades_df['trade_duration'] = (trades_df['exit_date'] - trades_df['entry_date']).dt.days

    num_trades = len(trades_df)
    wins = trades_df[trades_df['trade_return'] > 0]
    win_rate = len(wins) / num_trades * 100 if num_trades > 0 else np.nan
    best_trade = trades_df['trade_return'].max()
    worst_trade = trades_df['trade_return'].min()
    avg_trade = trades_df['trade_return'].mean()
    max_trade_duration = trades_df['trade_duration'].max()
    avg_trade_duration = trades_df['trade_duration'].mean()

    gross_profit = wins['trade_return'].sum()
    gross_loss = trades_df[trades_df['trade_return'] < 0]['trade_return'].sum()
    profit_factor = (gross_profit / -gross_loss) if gross_loss != 0 else np.nan

    expectancy = avg_trade * (win_rate / 100) + (worst_trade) * (1 - win_rate / 100)

    # SQN calculation: SQN = (mean trade return / std trade return) * sqrt(num trades)
    std_trade_return = trades_df['trade_return'].std()
    sqn = (avg_trade / std_trade_return) * np.sqrt(num_trades) if std_trade_return != 0 else np.nan

    # Kelly Criterion: k = win_rate - (loss_rate / payoff_ratio)
    loss_rate = 1 - win_rate / 100
    payoff_ratio = (wins['trade_return'].mean() / abs(trades_df[trades_df['trade_return'] < 0]['trade_return'].mean())) if len(wins) > 0 else np.nan
    if payoff_ratio and payoff_ratio > 0:
        kelly = (win_rate / 100) - (loss_rate / payoff_ratio)
    else:
        kelly = np.nan

    return {
        'Number of Trades': num_trades,
        'Win Rate [%]': win_rate,
        'Best Trade [%]': best_trade,
        'Worst Trade [%]': worst_trade,
        'Average Trade [%]': avg_trade,
        'Max Trade Duration (days)': max_trade_duration,
        'Average Trade Duration (days)': avg_trade_duration,
        'Profit Factor': profit_factor,
        'Expectancy [%]': expectancy,
        'SQN': sqn,
        'Kelly Criterion': kelly,
    }

In [114]:
def build_benchmarks(trade, train):
    price_df = trade.pivot(index='date', columns='tic', values='close').sort_index()
    price_df.index = pd.to_datetime(price_df.index)

    df_mvo, df_ew, df_bh, mvo_weights = build_mvo_and_baselines(train, price_df)

    # Download DJIA data (ticker: ^DJI)
    djia = yf.download('^DJI', start='2023-06-01', end='2025-01-01', progress=False)
    
    # Reset index to convert DatetimeIndex into 'date' column
    df_reset = djia.reset_index()
    
    # Extract only 'Date' and 'Close' columns and rename
    df_djia = df_reset[['Date', 'Close']].copy()
    df_djia.columns = ['date', 'account_value']
    
    # Ensure 'date' column is datetime dtype (should already be)
    df_djia['date'] = pd.to_datetime(df_djia['date'])
    
    # Normalize to initial capital (e.g., 1,000,000)
    initial_capital = 1_000_000
    first_close = df_djia['account_value'].iloc[0]
    
    df_djia['account_value'] = df_djia['account_value'] / first_close * initial_capital

    return df_mvo, df_ew, df_bh, df_djia

In [115]:
def analysis_metrics_rl_benchmarks(df_rl, df_mvo, df_ew, df_bh, df_djia):
    metrics_rl = calculate_metrics(df_rl)
    metrics_dija = calculate_metrics(df_djia)
    metrics_mvo = calculate_metrics(df_mvo)
    metrics_ew = calculate_metrics(df_ew)
    metrics_bh = calculate_metrics(df_bh)

    all_metrics = {
        'RL': metrics_rl,
        "DIJA": metrics_dija,
        'MVO': metrics_mvo,
        'EW': metrics_ew,
        'BH': metrics_bh
    }
    
    # Create DataFrame
    df_metrics = pd.DataFrame(all_metrics)

    return df_metrics, all_metrics

In [116]:
def analysis_trade_metrics(trade, df_actions):
    # Convert 'date' to datetime
    trade['date'] = pd.to_datetime(trade['date'])
    
    # Pivot to get prices by date and ticker
    df_prices = trade.pivot(index='date', columns='tic', values='close')
    
    # Sort index to ensure date order
    df_prices = df_prices.sort_index()

    # 1. Extract trades from positions and prices
    trades_df = extract_trades_from_positions(df_actions, df_prices)
    
    # 2. Calculate trade metrics
    trade_metrics = calculate_trade_metrics(trades_df)

    return trade_metrics

In [117]:
df = get_data(dataset="DOW_30", start_date=TRAIN_START_DATE, end_date=TRADE_END_DATE)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (110903, 8)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110903 entries, 0 to 110902
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    110903 non-null  datetime64[ns]
 1   close   110903 non-null  float64
 2   high    110903 non-null  float64
 3   low     110903 non-null  float64
 4   open    110903 non-null  float64
 5   volume  110903 non-null  int64
 6   tic     110903 non-null  object
 7   day     110903 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(1), object(1)
memory usage: 6.3+ MB

In [119]:
df = clean_data(df)

In [120]:
df = add_indicators(df, "DOW_30")

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)

In [121]:
df = add_vix(df)

In [122]:
df = add_turbulence(df)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107735 entries, 0 to 107734
Data columns (total 26 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   date         107735 non-null  datetime64[ns]
 1   close        107735 non-null  float64
 2   high         107735 non-null  float64
 3   low          107735 non-null  float64
 4   open         107735 non-null  float64
 5   volume       107735 non-null  int64
 6   tic          107735 non-null  object
 7   day          107735 non-null  int32
 8   sma_20       107735 non-null  float64
 9   sma_60       107735 non-null  float64
 10  ema_20       107735 non-null  float64
 11  macd         107735 non-null  float64
 12  macd_signal  107735 non-null  float64
 13  rsi_14       107735 non-null  float64
 14  stoch_k      107735 non-null  float64
 15  stoch_d      107735 non-null  float64
 16  cci_14       107735 non-null  float64
 17  adx_14       107735 non-null  float64
 18  boll_ub      107735 non-null  float64
 19  boll_lb      107735 non-null  float64
 20  boll_width   107735 non-null  float64
 21  atr_14       107735 non-null  float64
 22  obv          107735 non-null  int64
 23  vol_sma_20   107735 non-null  float64
 24  vix          107735 non-null  float64
 25  turbulence   107735 non-null  float64
dtypes: datetime64[ns](1), float64(21), int32(1), int64(2), object(1)
memory usage: 21.0+ MB

In [124]:
df

,date,close,high,low,open,volume,tic,day,sma_20,sma_60,...,cci_14,adx_14,boll_ub,boll_lb,boll_width,atr_14,obv,vol_sma_20,vix,turbulence
0,2010-03-30,7.088279,7.137268,7.040192,7.110820,527310000,AAPL,1,6.740568,6.324984,...,194.121734,29.722886,7.113102,6.368035,0.745067,0.125667,10326554000,530343660.0,17.129999,0.000000
1,2010-03-30,41.552101,41.676571,41.185608,41.358483,4360400,AMGN,1,40.346128,39.768727,...,78.133289,19.734636,42.013980,38.678275,3.335705,0.620006,51655000,6536700.0,17.129999,0.000000
2,2010-03-30,33.220741,33.381656,33.043735,33.236833,5561300,AXP,1,32.449730,31.889181,...,100.959892,18.795752,33.824839,31.074620,2.750219,0.658366,57318300,7852320.0,17.129999,0.000000
3,2010-03-30,57.688480,58.198444,57.037297,57.931691,4381300,BA,1,54.961760,50.054937,...,96.997028,53.480799,58.916866,51.006654,7.910212,1.178576,90713300,7416320.0,17.129999,0.000000
4,2010-03-30,42.795948,43.114411,42.558796,42.945016,6183200,CAT,1,40.868231,39.253975,...,107.305634,18.422733,43.043026,38.693435,4.349591,0.953868,92056700,8096300.0,17.129999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107730,2024-12-31,500.156769,505.238833,497.665191,503.607442,4214000,UNH,1,521.631494,558.723595,...,-4.199435,35.067087,592.562338,450.700650,141.861688,14.187482,946852200,7028345.0,17.350000,5.532019
107731,2024-12-31,314.985992,316.600585,314.138821,315.065712,3963800,V,1,313.540320,301.013719,...,-1.080068,21.798748,320.783638,306.297001,14.486637,4.554189,1702106700,6304385.0,17.350000,5.532019
107732,2024-12-31,38.057224,38.095288,37.638488,37.724138,13549900,VZ,1,39.174954,39.952176,...,-61.630413,25.200394,41.583253,36.766655,4.816599,0.589115,1117447218,17989470.0,17.350000,5.532019
107733,2024-12-31,9.330000,9.510000,9.220000,9.300000,12616500,WBA,1,9.454000,9.184771,...,-74.683951,28.918520,10.552133,8.355867,2.196266,0.494590,-860142200,25726540.0,17.350000,5.532019
107734,2024-12-31,89.885246,90.472215,89.596737,90.104116,11267700,WMT,1,92.862245,86.577602,...,-110.010608,37.261422,95.999429,89.725061,6.274368,1.600474,3640323100,18247770.0,17.350000,5.532019

In [125]:
df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")

In [126]:
list_ticker = df["tic"].unique().tolist()
list_date = list(pd.date_range(df['date'].min(), df['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination, columns=["date","tic"]).merge(df, on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(df['date'])]
processed_full = processed_full.sort_values(['date','tic'])

In [127]:
processed_full

,date,tic,close,high,low,open,volume,day,sma_20,sma_60,...,cci_14,adx_14,boll_ub,boll_lb,boll_width,atr_14,obv,vol_sma_20,vix,turbulence
0,2010-03-30,AAPL,7.088279,7.137268,7.040192,7.110820,527310000.0,1.0,6.740568,6.324984,...,194.121734,29.722886,7.113102,6.368035,0.745067,0.125667,1.032655e+10,530343660.0,17.129999,0.000000
1,2010-03-30,AMGN,41.552101,41.676571,41.185608,41.358483,4360400.0,1.0,40.346128,39.768727,...,78.133289,19.734636,42.013980,38.678275,3.335705,0.620006,5.165500e+07,6536700.0,17.129999,0.000000
2,2010-03-30,AXP,33.220741,33.381656,33.043735,33.236833,5561300.0,1.0,32.449730,31.889181,...,100.959892,18.795752,33.824839,31.074620,2.750219,0.658366,5.731830e+07,7852320.0,17.129999,0.000000
3,2010-03-30,BA,57.688480,58.198444,57.037297,57.931691,4381300.0,1.0,54.961760,50.054937,...,96.997028,53.480799,58.916866,51.006654,7.910212,1.178576,9.071330e+07,7416320.0,17.129999,0.000000
4,2010-03-30,CAT,42.795948,43.114411,42.558796,42.945016,6183200.0,1.0,40.868231,39.253975,...,107.305634,18.422733,43.043026,38.693435,4.349591,0.953868,9.205670e+07,8096300.0,17.129999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156334,2024-12-31,UNH,500.156769,505.238833,497.665191,503.607442,4214000.0,1.0,521.631494,558.723595,...,-4.199435,35.067087,592.562338,450.700650,141.861688,14.187482,9.468522e+08,7028345.0,17.350000,5.532019
156335,2024-12-31,V,314.985992,316.600585,314.138821,315.065712,3963800.0,1.0,313.540320,301.013719,...,-1.080068,21.798748,320.783638,306.297001,14.486637,4.554189,1.702107e+09,6304385.0,17.350000,5.532019
156336,2024-12-31,VZ,38.057224,38.095288,37.638488,37.724138,13549900.0,1.0,39.174954,39.952176,...,-61.630413,25.200394,41.583253,36.766655,4.816599,0.589115,1.117447e+09,17989470.0,17.350000,5.532019
156337,2024-12-31,WBA,9.330000,9.510000,9.220000,9.300000,12616500.0,1.0,9.454000,9.184771,...,-74.683951,28.918520,10.552133,8.355867,2.196266,0.494590,-8.601422e+08,25726540.0,17.350000,5.532019
156338,2024-12-31,WMT,89.885246,90.472215,89.596737,90.104116,11267700.0,1.0,92.862245,86.577602,...,-110.010608,37.261422,95.999429,89.725061,6.274368,1.600474,3.640323e+09,18247770.0,17.350000,5.532019

In [128]:
processed_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 107735 entries, 0 to 156338
Data columns (total 26 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   date         107735 non-null  object
 1   tic          107735 non-null  object
 2   close        107735 non-null  float64
 3   high         107735 non-null  float64
 4   low          107735 non-null  float64
 5   open         107735 non-null  float64
 6   volume       107735 non-null  float64
 7   day          107735 non-null  float64
 8   sma_20       107735 non-null  float64
 9   sma_60       107735 non-null  float64
 10  ema_20       107735 non-null  float64
 11  macd         107735 non-null  float64
 12  macd_signal  107735 non-null  float64
 13  rsi_14       107735 non-null  float64
 14  stoch_k      107735 non-null  float64
 15  stoch_d      107735 non-null  float64
 16  cci_14       107735 non-null  float64
 17  adx_14       107735 non-null  float64
 18  boll_ub      107735 non-null  float64
 19  boll_lb      107735 non-null  float64
 20  boll_width   107735 non-null  float64
 21  atr_14       107735 non-null  float64
 22  obv          107735 non-null  float64
 23  vol_sma_20   107735 non-null  float64
 24  vix          107735 non-null  float64
 25  turbulence   107735 non-null  float64
dtypes: float64(24), object(2)
memory usage: 22.2+ MB

In [129]:
TRAIN_START_DATE = '2010-01-01'
TRAIN_END_DATE = '2022-12-31'

TRADE_START_DATE= '2023-06-01'
TRADE_END_DATE = '2025-01-01'

train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)

In [130]:
train

,date,tic,close,high,low,open,volume,day,sma_20,sma_60,...,cci_14,adx_14,boll_ub,boll_lb,boll_width,atr_14,obv,vol_sma_20,vix,turbulence
0,2010-03-30,AAPL,7.088279,7.137268,7.040192,7.110820,527310000.0,1.0,6.740568,6.324984,...,194.121734,29.722886,7.113102,6.368035,0.745067,0.125667,1.032655e+10,530343660.0,17.129999,0.000000
0,2010-03-30,AMGN,41.552101,41.676571,41.185608,41.358483,4360400.0,1.0,40.346128,39.768727,...,78.133289,19.734636,42.013980,38.678275,3.335705,0.620006,5.165500e+07,6536700.0,17.129999,0.000000
0,2010-03-30,AXP,33.220741,33.381656,33.043735,33.236833,5561300.0,1.0,32.449730,31.889181,...,100.959892,18.795752,33.824839,31.074620,2.750219,0.658366,5.731830e+07,7852320.0,17.129999,0.000000
0,2010-03-30,BA,57.688480,58.198444,57.037297,57.931691,4381300.0,1.0,54.961760,50.054937,...,96.997028,53.480799,58.916866,51.006654,7.910212,1.178576,9.071330e+07,7416320.0,17.129999,0.000000
0,2010-03-30,CAT,42.795948,43.114411,42.558796,42.945016,6183200.0,1.0,40.868231,39.253975,...,107.305634,18.422733,43.043026,38.693435,4.349591,0.953868,9.205670e+07,8096300.0,17.129999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3212,2022-12-30,UNH,508.466766,508.773668,503.345496,508.294145,1849600.0,4.0,511.392764,507.353240,...,-20.959823,11.129882,525.665311,497.120218,28.545092,9.182283,9.366010e+08,2519705.0,21.670000,5.189347
3212,2022-12-30,V,203.877365,204.152131,201.855865,202.454466,4159400.0,4.0,204.935207,198.545542,...,-19.362095,10.115565,211.966549,197.903864,14.062685,3.965113,1.291124e+09,6276380.0,21.670000,5.189347
3212,2022-12-30,VZ,32.747978,32.989014,32.473692,32.673173,44007200.0,4.0,31.467982,31.242874,...,134.195078,15.783639,32.797224,30.138740,2.658484,0.672522,5.441826e+08,26737545.0,21.670000,5.189347
3212,2022-12-30,WBA,32.217495,32.234742,31.881178,32.114014,5406200.0,4.0,34.140537,32.465041,...,-123.988864,26.034008,36.415565,31.865509,4.550056,0.772035,1.754005e+08,5372865.0,21.670000,5.189347
3212,2022-12-30,WMT,45.765244,45.829800,45.448934,45.691010,11505900.0,4.0,47.032146,46.007580,...,-106.211076,19.997168,49.060203,45.004088,4.056115,0.754162,2.559837e+09,17969655.0,21.670000,5.189347

In [131]:
trade

,date,tic,close,high,low,open,volume,day,sma_20,sma_60,...,cci_14,adx_14,boll_ub,boll_lb,boll_width,atr_14,obv,vol_sma_20,vix,turbulence
0,2023-06-01,AAPL,178.304749,178.334450,175.176070,175.938441,68901800.0,3.0,171.818938,163.691484,...,163.777646,29.861607,177.431591,166.206285,11.225306,2.636191,1.839275e+10,58911595.0,15.65,54.553420
0,2023-06-01,AMGN,201.285034,207.231432,198.880175,206.630217,4831400.0,3.0,211.781760,219.574449,...,-124.999489,39.201448,222.712029,200.851491,21.860538,4.294894,3.900819e+08,2430195.0,15.65,54.553420
0,2023-06-01,AXP,158.288666,159.524084,153.920936,154.728335,4087200.0,3.0,148.629578,154.151966,...,178.643843,20.275383,156.182049,141.077108,15.104941,3.618498,2.078569e+08,3005975.0,15.65,54.553420
0,2023-06-01,BA,207.960007,210.229996,206.000000,206.460007,5125100.0,3.0,202.589001,204.702833,...,123.871831,9.499376,208.995404,196.182598,12.812806,4.829191,4.634223e+08,4487135.0,15.65,54.553420
0,2023-06-01,CAT,201.249329,202.693218,198.332658,199.911310,2989100.0,3.0,203.576379,209.456358,...,-92.549688,16.888665,208.559332,198.593427,9.965905,4.737930,2.005821e+08,2940410.0,15.65,54.553420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,2024-12-31,UNH,500.156769,505.238833,497.665191,503.607442,4214000.0,1.0,521.631494,558.723595,...,-4.199435,35.067087,592.562338,450.700650,141.861688,14.187482,9.468522e+08,7028345.0,17.35,5.532019
398,2024-12-31,V,314.985992,316.600585,314.138821,315.065712,3963800.0,1.0,313.540320,301.013719,...,-1.080068,21.798748,320.783638,306.297001,14.486637,4.554189,1.702107e+09,6304385.0,17.35,5.532019
398,2024-12-31,VZ,38.057224,38.095288,37.638488,37.724138,13549900.0,1.0,39.174954,39.952176,...,-61.630413,25.200394,41.583253,36.766655,4.816599,0.589115,1.117447e+09,17989470.0,17.35,5.532019
398,2024-12-31,WBA,9.330000,9.510000,9.220000,9.300000,12616500.0,1.0,9.454000,9.184771,...,-74.683951,28.918520,10.552133,8.355867,2.196266,0.494590,-8.601422e+08,25726540.0,17.35,5.532019
398,2024-12-31,WMT,89.885246,90.472215,89.596737,90.104116,11267700.0,1.0,92.862245,86.577602,...,-110.010608,37.261422,95.999429,89.725061,6.274368,1.600474,3.640323e+09,18247770.0,17.35,5.532019

In [132]:
def create_env(train, _ind, _hmax, _initial_amount, _reward_scaling):
    stock_dimension = len(train.tic.unique())
    state_space = 1 + 2 * stock_dimension + len(_ind) * stock_dimension
    print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")
    
    buy_cost_list = sell_cost_list = [0.001] * stock_dimension
    num_stock_shares = [0] * stock_dimension
    
    env_kwargs = {
        "hmax": _hmax,
        "initial_amount": _initial_amount,
        "num_stock_shares": num_stock_shares,
        "buy_cost_pct": buy_cost_list,
        "sell_cost_pct": sell_cost_list,
        "state_space": state_space,
        "stock_dim": stock_dimension,
        "tech_indicator_list": _ind,
        "action_space": stock_dimension,
        "reward_scaling": _reward_scaling
    }
    
    e_train_gym = StockTradingEnv(df = train, **env_kwargs)
    
    env_train, _ = e_train_gym.get_sb_env()
    return env_train, env_kwargs

In [133]:
def run_wandb(env_kwargs, _name, algorithm, _turbulence_threshold, _risk_indicator_col, _total_timesteps, params, _notes=""):
    run = wandb.init(
        entity="influx_m",
        project="RL-Finance-DOW30",
        name=_name,
        group=algorithm,
        job_type="train",
        tags=["rl", algorithm, "stock-trading"],
        notes=_notes,
        sync_tensorboard=True,
        config={  # <-- fixed comma here
            # Environment parameters
            "hmax": env_kwargs["hmax"],
            "initial_amount": env_kwargs["initial_amount"],
            "num_stock_shares": env_kwargs["num_stock_shares"],
            "buy_cost_pct": env_kwargs["buy_cost_pct"],
            "sell_cost_pct": env_kwargs["sell_cost_pct"],
            "state_space": env_kwargs["state_space"],
            "stock_dim": env_kwargs["stock_dim"],
            "tech_indicator_list": env_kwargs["tech_indicator_list"],
            "action_space": env_kwargs["action_space"],
            "reward_scaling": env_kwargs["reward_scaling"],
            "turbulence_threshold": _turbulence_threshold,
            "risk_indicator_col": _risk_indicator_col,
            "total_timesteps": _total_timesteps,
            "params_model": params
        },
        dir="./wandb_logs",
        mode="online",
    )
    
    return run

In [134]:
def run_model(algorithm, _total_timesteps):
    wandb_callback = WandbCallback(
        model_save_path="./models/",
        verbose=2,
        model_save_freq=10000,
    )
        
    tmp_path = f'./{algorithm}'
    
    agent = DRLAgent(env=env_train)
    model = agent.get_model(algorithm, tensorboard_log=tmp_path)
    
    new_logger = configure(tmp_path, ["stdout", "csv", "tensorboard"])
    model.set_logger(new_logger)
    
    trained = agent.train_model(
        model=model,
        tb_log_name=algorithm,
        total_timesteps=_total_timesteps,
        callbacks=[wandb_callback]
    )

    return trained, model

In [135]:
def backtest(trained, train, trade, _ind, _hmax, _initial_amount, _reward_scaling, _turbulence_threshold, _risk_indicator_col):
    stock_dimension = len(trade.tic.unique())
    state_space = 1 + 2 * stock_dimension + len(_ind) * stock_dimension
    print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")
    
    buy_cost_list = sell_cost_list = [0.001] * stock_dimension
    num_stock_shares = [0] * stock_dimension
    
    env_kwargs = {
        "hmax": _hmax,
        "initial_amount": _initial_amount,
        "num_stock_shares": num_stock_shares,
        "buy_cost_pct": buy_cost_list,
        "sell_cost_pct": sell_cost_list,
        "state_space": state_space,
        "stock_dim": stock_dimension,
        "tech_indicator_list": _ind,
        "action_space": stock_dimension,
        "reward_scaling": _reward_scaling
    }
    
    e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 70, risk_indicator_col='turbulence', **env_kwargs)
    
    df_account_value, df_actions = DRLAgent.DRL_prediction(
        model=trained,
        environment = e_trade_gym)

    return e_trade_gym, df_account_value, df_actions

In [136]:
def analysis_backtest(trade, train, df_account_value, df_actions):
    df_mvo, df_ew, df_bh, df_djia = build_benchmarks(trade, train)
    df_result, results = analysis_metrics_rl_benchmarks(df_account_value, df_mvo, df_ew, df_bh, df_djia)
    trade_metrics = analysis_trade_metrics(trade, df_actions)

    return df_result, results, trade_metrics

In [155]:
# Algorithms to run
ALGORITHMS = ["ppo", "a2c", "trpo", "td3", "sac", "rppo", "crossq"]

TOT_TIMESTEPS = {
    "a2c": 100_000,           # on-policy, needs many steps
    "ppo": 300_000,           # stable, multiple epochs over data
    "trpo": 300_000,          # similar to PPO but slower updates
    "recurrent_ppo": 300_000, # needs sequence data, similar to PPO
    "td3": 150_000,           # off-policy, more sample efficient
    "sac": 150_000,           # off-policy, stable and efficient
    "crossq": 150_000,        # off-policy, similar to SAC/TD3
}

# Your fixed parameters (except algorithm-specific ones)
params = {
    "ind_train": INDICATORS_DOW_30,
    "hmax_train": 100,
    "initial_amount_train": 1_000_000,
    "reward_scaling_train": 1e-4,
    "hmax_test": 100,
    "initial_amount_test": 1_000_000,
    "reward_scaling_test": 1e-4,
    "turbulence_threshold_test": 70,
    "risk_indicator_col_test": "vix",
}

In [ ]:
# Store all results here
all_results = {}

for algo in ALGORITHMS:
    print(f"\n=== Starting {algo.upper()} ===")

    # Step 1: Create environment kwargs for training
    env_train, env_kwargs = create_env(
        train,
        params["ind_train"],
        params["hmax_train"],
        params["initial_amount_train"],
        params["reward_scaling_train"]
    )
    print("Step 1 done: Environment created")

    # Step 2: Initialize wandb run
    run = run_wandb(
        env_kwargs,
        f"init {algo}",
        algo,
        params["turbulence_threshold_test"],
        params["risk_indicator_col_test"],
        TOT_TIMESTEPS[algo],
        DEFAULT_PARAMS[algo],
        _notes=f"Training {algo}"
    )
    print("Step 2 done: wandb run initialized")

    # Step 3: Train the model
    trained_model, model = run_model(algo, TOT_TIMESTEPS[algo])
    print("Step 3 done: Model trained")

    # Step 4: Backtest the trained model
    e_trade_gym, df_value, df_actions = backtest(
        trained_model,
        train,
        trade,
        params["ind_train"],
        params["hmax_test"],
        params["initial_amount_test"],
        params["reward_scaling_test"],
        params["turbulence_threshold_test"],
        params["risk_indicator_col_test"]
    )
    print("Step 4 done: Backtest completed")

    # Step 5: Analyze backtest results
    df_res, res, trade_metrics = analysis_backtest(trade, train, df_value, df_actions)
    print("Step 5 done: Backtest analysis completed")

    # Step 6: Log results to wandb
    run.log(res['RL'])
    run.log(trade_metrics)
    print("Step 6 done: Results logged to wandb")

    # Step 7: Save results in dict for later use
    all_results[algo] = {
        "df_res": df_res,
        "res": res,
        "trade_metrics": trade_metrics,
    }
    print(f"Step 7 done: Results saved for {algo.upper()}")

=== Starting PPO ===
Stock Dimension: 29, State Space: 523
Step 1 done: Environment created

wandb: WARNING When using several event log directories, please call `wandb.tensorboard.patch(root_logdir="...")` before `wandb.init`

Step 2 done: wandb run initialized
{'n_steps': 2048, 'batch_size': 256, 'gamma': 0.995, 'learning_rate': 0.00025, 'ent_coef': 0.01, 'clip_range': 0.2, 'n_epochs': 10, 'gae_lambda': 0.95, 'max_grad_norm': 0.5}
Using cuda device
Logging to ./ppo
-----------------------------------------
| actions/               |              |
|    max                 | 3.92         |
|    mean                | -0.00738     |
|    min                 | -4.16        |
|    std                 | 1            |
| time/                  |              |
|    fps                 | 105          |
|    iterations          | 1            |
|    time_elapsed        | 19           |
|    total_timesteps     | 2048         |
|    training_start      | 1.75e+09     |
| train/                 |              |
|    learning_rate       | 0.00025      |
|    rollout_reward_max  | 6.57         |
|    rollout_reward_mean | 0.0708       |
|    rollout_reward_min  | -10.8        |
|    step_reward         | -0.122295894 |
-----------------------------------------
-----------------------------------------
| actions/                |             |
|    max                  | 4.2         |
|    mean                 | 0.00431     |
|    min                  | -3.9        |
|    std                  | 1           |
| time/                   |             |
|    fps                  | 104         |
|    iterations           | 2           |
|    time_elapsed         | 39          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.011610528 |
|    clip_fraction        | 0.13        |
|    clip_range           | 0.2         |
|    entropy_loss         | -41.2       |
|    episode_length       | 1           |
|    episode_reward       | -0.00844    |
|    explained_variance   | -0.00486    |
|    learning_rate        | 0.00025     |
|    loss                 | 4.94        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0179     |
|    rollout_reward_max   | 20.1        |
|    rollout_reward_mean  | 0.0703      |
|    rollout_reward_min   | -32.1       |
|    std                  | 1           |
|    step_reward          | 1.5572876   |
|    value_loss           | 9.98        |
-----------------------------------------
----------------------------------------
| actions/                |            |
|    max                  | 4.55       |
|    mean                 | -0.00077   |
|    min                  | -4.29      |
|    std                  | 1          |
| time/                   |            |
|    fps                  | 103        |
|    iterations           | 3          |
|    time_elapsed         | 59         |
|    total_timesteps      | 6144       |
| train/                  |            |
|    approx_kl            | 0.01262436 |
|    clip_fraction        | 0.117      |
|    clip_range           | 0.2        |
|    entropy_loss         | -41.2      |
|    explained_variance   | 0.00891    |
|    learning_rate        | 0.00025    |
|    loss                 | 39         |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0187    |
|    rollout_reward_max   | 33.8       |
|    rollout_reward_mean  | 0.188      |
|    rollout_reward_min   | -43.3      |
|    std                  | 1          |
|    step_reward          | -3.3687844 |
|    value_loss           | 58.6       |
----------------------------------------
-----------------------------------------
| actions/                |             |
|    max                  | 4.13        |
|    mean                 | 0.0059      |
|    min                  | -4.52       |
|    std                  | 1.01        |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 4           |
|    time_elapsed         | 78          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.012115706 |
|    clip_fraction        | 0.0705      |
|    clip_range           | 0.2         |
|    entropy_loss         | -41.3       |
|    episode_length       | 1           |
|    episode_reward       | -0.0164     |
|    explained_variance   | -0.00258    |
|    learning_rate        | 0.00025     |
|    loss                 | 36          |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0107     |
|    rollout_reward_max   | 13.8        |
|    rollout_reward_mean  | 0.0476      |
|    rollout_reward_min   | -19         |
|    std                  | 1           |
|    step_reward          | 0.71183544  |
|    value_loss           | 83.4        |
-----------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 3.72        |
|    mean                  | 0.00646     |
|    min                   | -3.72       |
|    std                   | 1.02        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 5           |
|    time_elapsed          | 98          |
|    total_timesteps       | 10240       |
| train/                   |             |
|    approx_kl             | 0.013497012 |
|    clip_fraction         | 0.135       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.3       |
|    episode_length        | 1           |
|    episode_reward        | -0.0155     |
|    episode_reward_mean_5 | 139         |
|    explained_variance    | 0.00536     |
|    learning_rate         | 0.00025     |
|    loss                  | 17.1        |
|    n_updates             | 40          |
|    policy_gradient_loss  | -0.0258     |
|    rollout_reward_max    | 25.8        |
|    rollout_reward_mean   | 0.086       |
|    rollout_reward_min    | -38.1       |
|    std                   | 1.01        |
|    step_reward           | 0.087093726 |
|    value_loss            | 48.9        |
------------------------------------------
-----------------------------------------
| actions/                |             |
|    max                  | 4.22        |
|    mean                 | -0.00161    |
|    min                  | -3.89       |
|    std                  | 1.01        |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 6           |
|    time_elapsed         | 118         |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.012613175 |
|    clip_fraction        | 0.13        |
|    clip_range           | 0.2         |
|    entropy_loss         | -41.4       |
|    explained_variance   | 0.0208      |
|    learning_rate        | 0.00025     |
|    loss                 | 36.6        |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0209     |
|    rollout_reward_max   | 27.1        |
|    rollout_reward_mean  | 0.0917      |
|    rollout_reward_min   | -32.9       |
|    std                  | 1.01        |
|    step_reward          | -4.74834    |
|    value_loss           | 86.9        |
-----------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 4.11        |
|    mean                  | 0.00684     |
|    min                   | -4.99       |
|    std                   | 1.01        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 7           |
|    time_elapsed          | 138         |
|    total_timesteps       | 14336       |
| train/                   |             |
|    approx_kl             | 0.013794474 |
|    clip_fraction         | 0.153       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.4       |
|    episode_length        | 1           |
|    episode_reward        | -0.0223     |
|    episode_reward_mean_5 | 114         |
|    explained_variance    | 0.0212      |
|    learning_rate         | 0.00025     |
|    loss                  | 31.5        |
|    n_updates             | 60          |
|    policy_gradient_loss  | -0.0161     |
|    rollout_reward_max    | 13          |
|    rollout_reward_mean   | 0.0793      |
|    rollout_reward_min    | -14.5       |
|    std                   | 1.01        |
|    step_reward           | 1.8998697   |
|    value_loss            | 47.7        |
------------------------------------------
-------------------------------------------
| actions/                 |              |
|    max                   | 3.71         |
|    mean                  | 0.0178       |
|    min                   | -3.67        |
|    std                   | 1.03         |
| time/                    |              |
|    fps                   | 103          |
|    iterations            | 8            |
|    time_elapsed          | 158          |
|    total_timesteps       | 16384        |
| train/                   |              |
|    approx_kl             | 0.012866251  |
|    clip_fraction         | 0.127        |
|    clip_range            | 0.2          |
|    entropy_loss          | -41.5        |
|    episode_length        | 1            |
|    episode_reward        | -0.017       |
|    episode_reward_mean_5 | 118          |
|    explained_variance    | 0.0576       |
|    learning_rate         | 0.00025      |
|    loss                  | 18.4         |
|    n_updates             | 70           |
|    policy_gradient_loss  | -0.0236      |
|    rollout_reward_max    | 31.3         |
|    rollout_reward_mean   | 0.112        |
|    rollout_reward_min    | -33.4        |
|    std                   | 1.01         |
|    step_reward           | -0.090639666 |
|    value_loss            | 29.2         |
-------------------------------------------
------------------------------------------
| actions/                |              |
|    max                  | 4.21         |
|    mean                 | 0.00855      |
|    min                  | -4.81        |
|    std                  | 1.02         |
| time/                   |              |
|    fps                  | 103          |
|    iterations           | 9            |
|    time_elapsed         | 178          |
|    total_timesteps      | 18432        |
| train/                  |              |
|    approx_kl            | 0.0123322215 |
|    clip_fraction        | 0.109        |
|    clip_range           | 0.2          |
|    entropy_loss         | -41.5        |
|    explained_variance   | 0.0385       |
|    learning_rate        | 0.00025      |
|    loss                 | 32.2         |
|    n_updates            | 80           |
|    policy_gradient_loss | -0.016       |
|    rollout_reward_max   | 14.1         |
|    rollout_reward_mean  | 0.12         |
|    rollout_reward_min   | -13.3        |
|    std                  | 1.01         |
|    step_reward          | -8.0443535   |
|    value_loss           | 66.6         |
------------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 4.07        |
|    mean                  | 0.0126      |
|    min                   | -4.19       |
|    std                   | 1.02        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 10          |
|    time_elapsed          | 198         |
|    total_timesteps       | 20480       |
| train/                   |             |
|    approx_kl             | 0.013621301 |
|    clip_fraction         | 0.112       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.6       |
|    episode_length        | 1           |
|    episode_reward        | -0.0224     |
|    episode_reward_mean_5 | 142         |
|    explained_variance    | 0.0966      |
|    learning_rate         | 0.00025     |
|    loss                  | 10.4        |
|    n_updates             | 90          |
|    policy_gradient_loss  | -0.0182     |
|    rollout_reward_max    | 28.9        |
|    rollout_reward_mean   | 0.122       |
|    rollout_reward_min    | -36.1       |
|    std                   | 1.01        |
|    step_reward           | 2.8133607   |
|    value_loss            | 20.4        |
------------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 3.44        |
|    mean                  | 0.0368      |
|    min                   | -3.05       |
|    std                   | 1           |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 11          |
|    time_elapsed          | 217         |
|    total_timesteps       | 22528       |
| train/                   |             |
|    approx_kl             | 0.013113372 |
|    clip_fraction         | 0.119       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.6       |
|    episode_length        | 1           |
|    episode_reward        | -0.0192     |
|    episode_reward_mean_5 | 159         |
|    explained_variance    | 0.045       |
|    learning_rate         | 0.00025     |
|    loss                  | 43.9        |
|    n_updates             | 100         |
|    policy_gradient_loss  | -0.0192     |
|    rollout_reward_max    | 36.1        |
|    rollout_reward_mean   | 0.14        |
|    rollout_reward_min    | -41.7       |
|    std                   | 1.02        |
|    step_reward           | 0.55822223  |
|    value_loss            | 80.9        |
------------------------------------------
-----------------------------------------
| actions/                |             |
|    max                  | 4.22        |
|    mean                 | 0.0238      |
|    min                  | -4.37       |
|    std                  | 1.03        |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 12          |
|    time_elapsed         | 237         |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.012466117 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -41.7       |
|    explained_variance   | 0.0231      |
|    learning_rate        | 0.00025     |
|    loss                 | 39.8        |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.018      |
|    rollout_reward_max   | 9.9         |
|    rollout_reward_mean  | 0.115       |
|    rollout_reward_min   | -14.9       |
|    std                  | 1.02        |
|    step_reward          | -3.096586   |
|    value_loss           | 93          |
-----------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 4.63        |
|    mean                  | 0.0209      |
|    min                   | -4.36       |
|    std                   | 1.02        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 13          |
|    time_elapsed          | 257         |
|    total_timesteps       | 26624       |
| train/                   |             |
|    approx_kl             | 0.014873276 |
|    clip_fraction         | 0.146       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.7       |
|    episode_length        | 1           |
|    episode_reward        | -0.0176     |
|    episode_reward_mean_5 | 156         |
|    explained_variance    | 0.23        |
|    learning_rate         | 0.00025     |
|    loss                  | 9.22        |
|    n_updates             | 120         |
|    policy_gradient_loss  | -0.023      |
|    rollout_reward_max    | 30.3        |
|    rollout_reward_mean   | 0.113       |
|    rollout_reward_min    | -49.3       |
|    std                   | 1.02        |
|    step_reward           | 0.78575516  |
|    value_loss            | 17.5        |
------------------------------------------
-----------------------------------------
| actions/                |             |
|    max                  | 4.63        |
|    mean                 | 0.00747     |
|    min                  | -4.36       |
|    std                  | 1.03        |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 14          |
|    time_elapsed         | 277         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.010882263 |
|    clip_fraction        | 0.0959      |
|    clip_range           | 0.2         |
|    entropy_loss         | -41.8       |
|    explained_variance   | 0.065       |
|    learning_rate        | 0.00025     |
|    loss                 | 39.3        |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0198     |
|    rollout_reward_max   | 24.3        |
|    rollout_reward_mean  | 0.126       |
|    rollout_reward_min   | -30.9       |
|    std                  | 1.02        |
|    step_reward          | 3.5699604   |
|    value_loss           | 91.8        |
-----------------------------------------
day: 3212, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 4438702.70
total_reward: 3438702.70
total_cost: 407798.94
total_trades: 86638
Sharpe: 0.801
=================================
------------------------------------------
| actions/                 |             |
|    max                   | 4.39        |
|    mean                  | 0.0111      |
|    min                   | -4.34       |
|    std                   | 1.03        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 15          |
|    time_elapsed          | 297         |
|    total_timesteps       | 30720       |
| train/                   |             |
|    approx_kl             | 0.010678348 |
|    clip_fraction         | 0.0949      |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.9       |
|    episode_length        | 1           |
|    episode_reward        | -0.0126     |
|    episode_reward_mean_5 | 146         |
|    explained_variance    | -0.00165    |
|    learning_rate         | 0.00025     |
|    loss                  | 25.7        |
|    n_updates             | 140         |
|    policy_gradient_loss  | -0.0132     |
|    rollout_reward_max    | 11.4        |
|    rollout_reward_mean   | 0.0666      |
|    rollout_reward_min    | -15         |
|    std                   | 1.03        |
|    step_reward           | -0.31529343 |
|    value_loss            | 48.2        |
------------------------------------------
------------------------------------------
| actions/                 |             |
|    max                   | 4.13        |
|    mean                  | 0.0249      |
|    min                   | -3.79       |
|    std                   | 1.03        |
| time/                    |             |
|    fps                   | 103         |
|    iterations            | 16          |
|    time_elapsed          | 316         |
|    total_timesteps       | 32768       |
| train/                   |             |
|    approx_kl             | 0.014638828 |
|    clip_fraction         | 0.154       |
|    clip_range            | 0.2         |
|    entropy_loss          | -41.9       |
|    episode_length        | 1           |
|    episode_reward        | -0.0143     |
|    episode_reward_mean_5 | 117         |
|    explained_variance    | 0.154       |
|    learning_rate         | 0.00025     |
|    loss                  | 15.7        |
|    n_updates             | 150         |